### ISSUE TITLE
How to change table position?

### ISSUE THREAD

**Issue by mohindra9211** [py-pdf/fpdf2#1002]
How to Align an Image and a Table on the Same Row? Due to default table position is centered, causing alignment issues.

**Comment by Lutheine** [comment]
Hey, having the same issue, Y coordinate works, I can adjust on Y axis where table starts, but it's always centered.

**Comment by Lutheine** [comment]
Ok, I figured it out, param: 'align' = 'CENTER'  (and as well 'RIGHT') and is causing to override x value. Setting align = 'LEFT' (or 'X_CENTER') restores anchor to left edge and table gets you table in correct position on the page.

**Comment by gmischler** [comment]
Welcome to fpdf2, @mohindra9211 and @Lutheine!

Most FPDF methods will use the "current position" to place their elements on the page, but some you can also place explicitly. The `FPDF.x` and `FPDF.y` attributes defining the current position can either be set directly, or throught one of the [`set_x()`](https://py-pdf.github.io/fpdf2/fpdf/fpdf.html#fpdf.fpdf.FPDF.set_x), [`set_y()`](https://py-pdf.github.io/fpdf2/fpdf/fpdf.html#fpdf.fpdf.FPDF.set_y) and [`set_xy()`](https://py-pdf.github.io/fpdf2/fpdf/fpdf.html#fpdf.fpdf.FPDF.set_xy) methods. Many rendering methods will also move them, usually to the bottom of the added content.

The [`table()`](https://py-pdf.github.io/fpdf2/fpdf/fpdf.html#fpdf.fpdf.FPDF.table) method uses `FPDF.y` for vertical positioning, and the `align` argument for horizontal positioning between the side margins of the page.
You can place an image in any location by using the `x` and `y` arguments to the [`image()`](https://py-pdf.github.io/fpdf2/fpdf/fpdf.html#fpdf.fpdf.FPDF.image) method. You can also use one of the [`Align`](https://py-pdf.github.io/fpdf2/fpdf/enums.html#fpdf.enums.Align) values for the `x` argument, and it will behave similarly to `table()`.

**Comment by Lutheine** [comment]
Hi @gmischler, 

 [`table()`](https://py-pdf.github.io/fpdf2/fpdf/fpdf.html#fpdf.fpdf.FPDF.table) method param align acts not reliably when not using full page width. Have a look on below code:
 
```
from fpdf import FPDF
test = FPDF(orientation='landscape', unit='mm', format='A5')
test.add_page()
test.set_font('Helvetica', '')
test.set_font_size(8)
data = (('header1', 'header2', 'header3'), ('row1', 'row1', 'row1'), ('row2', 'row2', 'row2'), )

# table 1 with LEFT align does work with both set_x and set_y (same effect with align='X_CENTRE')
test.set_xy(5, 5)
with test.table(width=100, col_widths=(30, 50, 20), align='LEFT',borders_layout='All', line_height=1.5*label.font_size) as table:
    for data_row in data:
        row = table.row()
        for cell in data_row:
            row.cell(cell)


# table 2 with CENTRE align does work only with set_y, x position is overwritten (same effect with align='RIGHT')
test.set_xy(5, 105)
with test.table(width=100, col_widths=(30, 50, 20), align='CENTER',borders_layout='All', line_height=1.5*label.font_size) as table:
    for data_row in data:
        row = table.row()
        for cell in data_row:
            row.cell(cell)

test.output('test.pdf')
```

Above gives following output:
![image](https://github.com/py-pdf/fpdf2/assets/19671759/96f972c8-69e9-4bd5-bb98-8cee062b4085)


In my project, I need my table to be offset a bit (40mm) from left so I can fit a text field on left from the table. So this LEFT align with set_x(40) does the trick, but it's just inconsistent that 'LEFT' and 'X-CENTER' have different behavior than 'CENTER' and 'RIGTH'.

**Comment by Lucas-C** [comment]
First, thank you for reporting a potential issue here 😊

> [table()](https://py-pdf.github.io/fpdf2/fpdf/fpdf.html#fpdf.fpdf.FPDF.table) method param align acts not reliably when not using full page width.

I'm sorry but I do not understand you: how is page width related to your problem?

> # table 2 with CENTRE align does work only with set_y, x position is overwritten (same effect with align='RIGHT')

Yes, if you use `align=`, the current x position will be ignored. This is the expected behaviour.

> In my project, I need my table to be offset a bit (40mm) from left so I can fit a text field on left from the table. So this LEFT align with set_x(40) does the trick, but it's just inconsistent that 'LEFT' and 'X-CENTER' have different behavior than 'CENTER' and 'RIGTH'.

What is inconsistent exactly?
What would you expect to happen with `align="CENTER"`?

**Comment by gmischler** [comment]
>> [table()](https://py-pdf.github.io/fpdf2/fpdf/fpdf.html#fpdf.fpdf.FPDF.table) method param align acts not reliably when not using full page width.
>
> I'm sorry but I do not understand you: how is page width related to your problem?

The first line is an excerpt from the docstring. And no, I don't understand it either... :wink:

> Yes, if you use align=, the current x position will be ignored. This is the expected behaviour.

I don't see this inconsistend use of `FPDF.x` for table positioning understandably documented anywhere (I am guessing this is what the incomprehensible docstring above is trying to allude to, without actually saying it).

The current x position is most useful (and most easily understood) for the placement of running text. We should probably be careful about how we use it for other types of content.
Given that a table is rather a complex container than an actual content element (technically it is both), using the current x position for its placement is confusing, especially if it is not used consistently.
`text_columns()` has the additional arguments `l_margin` and `r_margin`, which can be used to override the page margins and solves the dilemma. That is very easy to understand and handle, and might work similarly well for tables. "How do I position a table" has been the most often asked question recently, so it should not be a backwards compatibility problem to change a type of behaviour that nobody understands anyway... :wink:

>>...but it's just inconsistent that 'LEFT' and 'X-CENTER' have different behavior than 'CENTER' and 'RIGTH'.

'X-Center' is supposed to center text around the current x position. This only really makes sense for text, so if given to a table it should raise an error.

**Comment by Lucas-C** [comment]
Hi @Lutheine @mohindra9211

Feedbacks and extra questions are welcome regarding this 😊

But without any answer from you we will close this issue at some point.
