### ISSUE TITLE
False positive when attempting to detect nested html tags

### ISSUE THREAD

**Issue by dmail00** [py-pdf/fpdf2#1010]
**Describe the bug**
I have reduced a html table which has worked in previous versions of fpdf to a minimal example to show the error. A row contains the encoded character '<' as "$lt;" in an element. However, when the write_html method is called the data is __corrected__ by calling :

```python
text = unescape(text) 
```

Hereby losing the information that this was a html less than encoded symbol and I believe this is incorrectly leading to the code assuming that a nested tag is present.

**Error details**

```
NotImplementedError: Unsupported nested HTML tags inside <td> element: <td>
```

**Minimal code**
```python
from fpdf import FPDF

pdf = FPDF()
pdf.add_page()
pdf.set_font("Helvetica", size=8)
pdf.write_html("""<table>
<thead>
    <tr>
        <th>Mark</th>
    </tr>
</thead>
<tbody>
    <tr>
        <td>&lt;      2</td>
    </tr>
</tbody>
</table>""")
pdf.output("test.pdf")
```

**Environment**
Please provide the following information:
* **Operating System**: Windows, 
* **Python version**: 3.11.3
* **`fpdf2` version used**:  fpdf2==2.7.6

**Comment by gmischler** [comment]
Thanks for reporting this bug, @dmail00 !

I think your analysis is correct. HTML content should not be unescaped at the before, but only after the HTML processing before passing the text data off to be rendered.

Are you interested to submit a PR with a fix?
