### ISSUE TITLE
adding an SVG image displays a black square

### ISSUE THREAD

**Issue by gbgssoftware** [py-pdf/fpdf2#1036]
Hello there! 
Thanks for the community members who develop and support fpdf2.

I'm using this version `pip install git+https://github.com/PyFPDF/fpdf2.git@master` and this code

```python
from fpdf import FPDF

def add_image(image_path):
     pdf = FPDF()
     pdf.allow_images_transparency = True
     pdf.add_page()
     pdf.image(image_path)
     pdf.output("doc-with-svg.pdf")

if __name__ == '__main__':
     image_path = '../1.svg'
     add_image(image_path)
```

When I open the pdf file, the image appears as a black square.

output pdf:
![image](https://github.com/py-pdf/fpdf2/assets/126825298/d7fd3d8c-6cf2-4cda-99c6-1e32042a0698)

svg image:
![2](https://github.com/py-pdf/fpdf2/assets/126825298/6196447e-9073-429f-886e-8211ba504b5d)

What can I do?

**Comment by Lucas-C** [comment]
Welcome and thank you for the report @gbgssoftware

Sadly, your SVG file depends heavily on the a `<style type="text/css">` tag defined on line 8.

CSS styling is part of the SVG features currently not supported by ``fpdf2 :
https://py-pdf.github.io/fpdf2/SVG.html#currently-unsupported-notable-svg-features

The only auick solution for you now is to modify your SVG file.
Here is a modified version that gets rendered perfectly well by `fpdf2`:
![issue-1036](https://github.com/py-pdf/fpdf2/assets/925560/af479033-9505-4b89-8cd8-de5a0a3dbd07)

```python
from fpdf import FPDF

pdf = FPDF()
pdf.add_page()
pdf.image("issue-1036.svg", w=pdf.epw)
pdf.output("issue_1036.pdf")
```

For the record, this SVG file seems to have been generated by CorelDRAW 2017

**Comment by gmischler** [comment]
FWIW, Firefox also displays the original file with a black square.

**Comment by gbgssoftware** [comment]
> Welcome and thank you for the report @gbgssoftware
> 
> Sadly, the visual rendering of your SVG file depends heavily on a `<style type="text/css">` tag defined on line 8.
> 
> CSS styling is one of the SVG features currently not supported by `fpdf2`: https://py-pdf.github.io/fpdf2/SVG.html#currently-unsupported-notable-svg-features
> 
> The only quick solution for you now is to modify your SVG file. Here is a modified version that gets rendered perfectly well by `fpdf2`: ![issue-1036](https://user-images.githubusercontent.com/925560/284701963-af479033-9505-4b89-8cd8-de5a0a3dbd07.svg)
> 
> ```python
> from fpdf import FPDF
> 
> pdf = FPDF()
> pdf.add_page()
> pdf.image("issue-1036.svg", w=pdf.epw)
> pdf.output("issue_1036.pdf")
> ```
> 
> For the record, this SVG file seems to have been generated by CorelDRAW 2017
> 
> You can also make a contribution to `fpdf2` and submit a PR to progressively add support for `<style>` SVG tags in `fpdf2`.
> 
> Does this comment answer your questions? 🙂

In the modified SVG,
the style and class tags have been removed.
Fill, stroke... tags added
Is there a way to convert these svg files?
Or would it be better to convert SVG to png and then add it to the PDF?

To make a contribution, I would like to :-)

Thanks

**Comment by Lucas-C** [comment]
> In the modified SVG,
> the style and class tags have been removed.
> Fill, stroke... tags added
> Is there a way to convert these svg files?

You'll have to do your own research on this, but a quick check on a web search engine reveals some options:
* https://stackoverflow.com/a/70490649/636849
* https://github.com/svg/svgo/blob/main/plugins/convertStyleToAttrs.js

> Or would it be better to convert SVG to png and then add it to the PDF?

Of course, that is an option.
But PNG is a raster image format, so you'll get a finite details resolution,
whereas SVG being vector graphics will not have this limitation (_i.e._ you can zoom forever an never see a pixel).
It's a matter of choice depending on your own needs.

> To make a contribution, I would like to :-)

You can start to read our documentation page on development guidelines:
<https://py-pdf.github.io/fpdf2/Development.html>

Second, you can read `fpdf2` code source, and get an understanding on how SVG files are rendered:
https://github.com/py-pdf/fpdf2/blob/master/fpdf/svg.py

**Comment by gbgssoftware** [comment]
If I use modified SVG, 


```
<?xml version="1.0" encoding="UTF-8"?>
<svg width="210mm" height="297mm" version="1.1" viewBox="0 0 21000 29700"
     xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <polygon fill="none" stroke="#2B2A29" stroke-width="7.62" stroke-miterlimit="22.9256" points="4500,7285.31 16500,7285.31 16500,22585.31 4500,22585.31 "/>
    <path fill="#2B2A29" stroke="#2B2A29" stroke-width="7.62" stroke-miterlimit="22.9256" d="M5292.26 20229.97l-242.33 0 0 1700.09 240.63 -0.09c-33.89,-562.95 -39.19,-1128.85 1.7,-1700z"/>
    <path fill="#2B2A29" stroke="#2B2A29" stroke-width="7.62" stroke-miterlimit="22.9256" d="M15707.77 20229.95l242.33 0 0 1700.09 -240.63 -0.09c33.89,-562.95 39.19,-1128.85 -1.7,-1700z"/>
    <path fill="#2B2A29" stroke="#2B2A29" stroke-width="7.62" stroke-miterlimit="22.9256" d="M5960.65 21926.54c-36.82,-560.5 -34.98,-1126.78 1,-1700l-303.32 0c35.98,573.22 37.62,1139.5 0.8,1700l301.52 0z"/>
    <path fill="#2B2A29" stroke="#2B2A29" stroke-width="7.62" stroke-miterlimit="22.9256" d="M6630.65 21926.54c-36.82,-560.5 -34.98,-1126.78 1,-1700l-303.32 0c35.98,573.22 37.62,1139.5 0.8,1700l301.52 0z"/>
    <path fill="#2B2A29" stroke="#2B2A29" stroke-width="7.62" stroke-miterlimit="22.9256" d="M7300.65 21926.54c-36.82,-560.5 -34.98,-1126.78 1,-1700l-303.32 0c35.98,573.22 37.62,1139.5 0.8,1700l301.52 0z"/>
    <path fill="#2B2A29" stroke="#2B2A29" stroke-width="7.62" stroke-miterlimit="22.9256" d="M7970.65 21926.54c-36.82,-560.5 -34.98,-1126.78 1,-1700l-303.32 0c35.98,573.22 37.62,1139.5 0.8,1700l301.52 0z"/>
    <path fill="#2B2A29" stroke="#2B2A29" stroke-width="7.62" stroke-miterlimit="22.9256" d="M8640.65 21926.54c-36.82,-560.5 -34.98,-1126.78 1,-1700l-303.32 0c35.98,573.22 37.62,1139.5 0.8,1700l301.52 0z"/>
    <path fill="#2B2A29" stroke="#2B2A29" stroke-width="7.62" stroke-miterlimit="22.9256" d="M9310.65 21926.54c-36.82,-560.5 -34.98,-1126.78 1,-1700l-303.32 0c35.98,573.22 37.62,1139.5 0.8,1700l301.52 0z"/>
    <path fill="#2B2A29" stroke="#2B2A29" stroke-width="7.62" stroke-miterlimit="22.9256" d="M9980.65 21926.54c-36.82,-560.5 -34.98,-1126.78 1,-1700l-303.32 0c35.98,573.22 37.62,1139.5 0.8,1700l301.52 0z"/>
    <path fill="#2B2A29" stroke="#2B2A29" stroke-width="7.62" stroke-miterlimit="22.9256" d="M10650.65 21926.54c-36.82,-560.5 -34.98,-1126.78 1,-1700l-303.32 0c35.98,573.22 37.62,1139.5 0.8,1700l301.52 0z"/>
    <path fill="#2B2A29" stroke="#2B2A29" stroke-width="7.62" stroke-miterlimit="22.9256" d="M11320.65 21926.54c-36.82,-560.5 -34.98,-1126.78 1,-1700l-303.32 0c35.98,573.22 37.62,1139.5 0.8,1700l301.52 0z"/>
    <path fill="#2B2A29" stroke="#2B2A29" stroke-width="7.62" stroke-miterlimit="22.9256" d="M11990.65 21926.54c-36.82,-560.5 -34.98,-1126.78 1,-1700l-303.32 0c35.98,573.22 37.62,1139.5 0.8,1700l301.52 0z"/>
    <path fill="#2B2A29" stroke="#2B2A29" stroke-width="7.62" stroke-miterlimit="22.9256" d="M12660.65 21926.54c-36.82,-560.5 -34.98,-1126.78 1,-1700l-303.32 0c35.98,573.22 37.62,1139.5 0.8,1700l301.52 0z"/>
    <path fill="#2B2A29" stroke="#2B2A29" stroke-width="7.62" stroke-miterlimit="22.9256" d="M13330.65 21926.54c-36.82,-560.5 -34.98,-1126.78 1,-1700l-303.32 0c35.98,573.22 37.62,1139.5 0.8,1700l301.52 0z"/>
    <path fill="#2B2A29" stroke="#2B2A29" stroke-width="7.62" stroke-miterlimit="22.9256" d="M14000.65 21926.54c-36.82,-560.5 -34.98,-1126.78 1,-1700l-303.32 0c35.98,573.22 37.62,1139.5 0.8,1700l301.52 0z"/>
    <path fill="#2B2A29" stroke="#2B2A29" stroke-width="7.62" stroke-miterlimit="22.9256" d="M14670.65 21926.54c-36.82,-560.5 -34.98,-1126.78 1,-1700l-303.32 0c35.98,573.22 37.62,1139.5 0.8,1700l301.52 0z"/>
    <path fill="#2B2A29" stroke="#2B2A29" stroke-width="7.62" stroke-miterlimit="22.9256" d="M15340.65 21926.54c-36.82,-560.5 -34.98,-1126.78 1,-1700l-303.32 0c35.98,573.22 37.62,1139.5 0.8,1700l301.52 0z"/>
    <path fill="#2B2A29" stroke="#2B2A29" stroke-width="7.62" stroke-miterlimit="22.9256" d="M5292.26 18049.97l-242.33 0 0 1700.09 240.63 -0.09c-33.89,-562.95 -39.19,-1128.85 1.7,-1700z"/>
    <path fill="#2B2A29" stroke="#2B2A29" stroke-width="7.62" stroke-miterlimit="22.9256" d="M15707.77 18049.95l242.33 0 0 1700.09 -240.63 -0.09c33.89,-562.95 39.19,-1128.85 -1.7,-1700z"/>
    <path fill="#2B2A29" stroke="#2B2A29" stroke-width="7.62" stroke-miterlimit="22.9256" d="M5960.65 19746.54c-36.82,-560.5 -34.98,-1126.78 1,-1700l-303.32 0c35.98,573.22 37.62,1139.5 0.8,1700l301.52 0z"/>
</svg>
```


I get the following error.



`Traceback (most recent call last):
  File "/usr/lib/python3.11/xml/etree/ElementTree.py", line 1709, in feed
    self.parser.Parse(data, False)
xml.parsers.expat.ExpatError: XML or text declaration not at start of entity: line 2, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tests/test_print_fpdf.py", line 19, in <module>
    pdf.image(image_path, w=pdf.epw)
  File "venv_amd/lib/python3.11/site-packages/fpdf/fpdf.py", line 217, in wrapper
    return fn(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv_amd/lib/python3.11/site-packages/fpdf/fpdf.py", line 3899, in image
    name, img, info = preload_image(self.image_cache, name, dims)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv_amd/lib/python3.11/site-packages/fpdf/image_parsing.py", line 89, in preload_image
    return get_svg_info(name, load_image(str(name)), image_cache=image_cache)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv_amd/lib/python3.11/site-packages/fpdf/image_parsing.py", line 192, in get_svg_info
    svg = SVGObject(img.getvalue(), image_cache=image_cache)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv_amd/lib/python3.11/site-packages/fpdf/svg.py", line 651, in __init__
    svg_tree = parse_xml_str(svg_text)  # nosec B314
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "venv_amd/lib/python3.11/site-packages/defusedxml/common.py", line 126, in fromstring
    parser.feed(text)
  File "/usr/lib/python3.11/xml/etree/ElementTree.py", line 1711, in feed
    self._raiseerror(v)
  File "/usr/lib/python3.11/xml/etree/ElementTree.py", line 1618, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: XML or text declaration not at start of entity: line 2, column 0`

What can I do?
Thanks

**Comment by Lucas-C** [comment]
@gbgssoftware : feel free to ask any questions you would have regarding this 🙂

Without any news from you, we will close this issue at some point.
