### ISSUE TITLE
Place image in a background page

### ISSUE THREAD

**Issue by gbgssoftware** [py-pdf/fpdf2#1047]
Greetings,
I create a PDF with custom dimensions.
Inside the page add an image (svg) of the same size as the PDF page.
The PDF page does not size correctly. The image is resized and positioned in the center.

**Minimal code**
```python
from fpdf import FPDF

image_path = '../t1.svg'
margin_top, margin_left, margin_right = (0, 0, 0)
pdf = FPDF(unit='mm')
pdf.set_margins(margin_left, margin_top, margin_right)
pdf.set_font('Helvetica', style='B', size=10)

pdf.add_page(format=(120,153))
pdf.image(image_path,  x=0, y=0, w=120, h=153)
pdf.output("target.pdf")
```

**Environment**
* **Operating System**: Linux
* **Python version**:3.11
* **`fpdf2` version used**: fpdf2 @ git+https://github.com/PyFPDF/fpdf2.git@c76329a894d6b362223b5189c6b0f7f1fba43754

What can I do?
Thanks

**Comment by Lucas-C** [comment]
Hi @gbgssoftware

You did not provide the `t1.svg` vector image you used in your sample code.
As a consequence, I cannot reproduce the problem that you are having, I'm sorry.

**Comment by gbgssoftware** [comment]
You are right :-)
![t1](https://github.com/py-pdf/fpdf2/assets/126825298/4a901baf-8ac8-468c-812a-ea01ee544203)

**Comment by Lucas-C** [comment]
Are you aware that this has already been reported ?
_cf._ https://github.com/py-pdf/fpdf2/issues/1036

Where is this image coming from?

**Comment by gbgssoftware** [comment]
Since they are two different problems, I thought it was correct to open two issues
In this svg file, there are no css styles

**Comment by Lucas-C** [comment]
We will be releasing a new version of `fpdf2` very soon.

Apart from that, is there anything else we can do regarding this @gbgssoftware?

**Comment by Lucas-C** [comment]
New release: https://github.com/py-pdf/fpdf2/releases/tag/2.7.7
