### ISSUE TITLE
Tables with multiple header rows and merging cells

### ISSUE THREAD

**Issue by mohindra9211** [py-pdf/fpdf2#1064]
How do I create a table that includes multiple headers, and what is the process for merging cells (**vertical merging**)? I've tried different methods, but so far, none have produced the expected results.

![tbl](https://github.com/py-pdf/fpdf2/assets/26268283/b1e8ca8c-0c5b-4947-8973-7f865a41ff97)

 **This is my code**

```
from fpdf import FPDF
from fpdf.fonts import FontFace

MULTI_HEADING_TABLE_DATA = (
    ("ID", "Category 1", "Category 2","Total"),
    ("ID", "Fruits", "Sales", "Vegetable", "Sales", "Total"),
    ("1", "A", "3", "4", "AA","25"),
    ("2", "B", "4", "5", "BB","38"),
    ("3", "C", "5", "6", "CC","40"),
)

pdf = FPDF()
pdf.set_font("Times", size=12)
pdf.add_page()

# Define the number of columns for each category
num_cols_per_category = [1, 2, 2,1]
headings_style = FontFace(color=(255,255,255), fill_color=(69, 69, 69))
with pdf.table(
    headings_style = headings_style,
    text_align="CENTER",
    cell_fill_color=230,
    cell_fill_mode="ROWS",
    borders_layout="MINIMAL",
    num_heading_rows=2,
) as table:
    for j, rowdata in enumerate(MULTI_HEADING_TABLE_DATA):
        if j == 0:
            # row with colspan
            row = table.row()
            for i, cell in enumerate(rowdata):
                row.cell(text=cell, colspan=num_cols_per_category[i])
        else:
            table.row(cells=rowdata)

# Save the PDF file
pdf.output("multi_heading_table.pdf")
```
**Code Output**
This is just an example; Please ignore the values ​​in the table.

![Screenshot 2023-12-14 150118](https://github.com/py-pdf/fpdf2/assets/26268283/28038375-483c-4cca-8abc-4e0dd71667d2)

**Comment by gmischler** [comment]
> How do I create a table that includes multiple headers, and what is the process for merging cells? I've tried different methods, but so far, none have produced the expected results.

So what exactly is the expected result?
If you're thinking about vertical merging of cells, rowspan is not currently supported.
As always, contributions are welcome.

**Comment by mjasperse** [comment]
I've been playing around with making a simple `rowspan` implementation. It's coming along pretty well, although verifying all the corner cases, adding appropriate tests and updating the documentation will take some time. It's in the works though.

![image](https://github.com/py-pdf/fpdf2/assets/146605/e4adbac4-39b8-4b32-acdf-3ae9d3b574aa)

**Comment by Lucas-C** [comment]
> I've been playing around with making a simple rowspan implementation. It's coming along pretty well, although verifying all the corner cases, adding appropriate tests and updating the documentation will take some time. It's in the works though.

Nice @mjasperse!

Would you like to submit a PR? 🙂

**Comment by mjasperse** [comment]
Yep, hoping to submit a PR with the rowspan implementation this week! The corner cases needed some thought, will probably need a bit of iteration - but I think I've got the most common use-cases covered.

e.g.
![image](https://github.com/py-pdf/fpdf2/assets/146605/d03eac77-61ac-48ee-b7ec-20dbbccc3bde)
