### ISSUE TITLE
Expected behaviour re outer table border with nonzero gutter?

### ISSUE THREAD

**Issue by mjasperse** [py-pdf/fpdf2#1071]
Hi guys,
Just wanted to clarify whether it is intended that the exterior border of a table is fragmented by the gutter. This seems like a bug to me, but the test suites have results committed indicating it is correct:

e.g. `test_outside_border_width()`
![image](https://github.com/py-pdf/fpdf2/assets/146605/a6fa55ba-e500-47dd-8371-1d65c14a6dc5)

e.g. `test_table_with_gutter_and_padding_and_outer_border_width()`
![image](https://github.com/py-pdf/fpdf2/assets/146605/144c68d5-0c14-4528-9740-6afc623fcb1d)

I've changed it in my local version, but if this is the intended result I will move the change to outside the library.

Cheers,
Martijn

**Comment by Lucas-C** [comment]
Hi @mjasperse and thank you for this report! 👍

To me this seems like a bug.
I looked at the existing test reference PDF files, and to me it would make more sense for them to have an "unbroken" outer border.

Pinging @RubendeBruin about this, as he contributed most of the padding implementation, and may have extra useful information to share regarding this 😊

But it'd be nice to see how you fixed that, so feel free to submit a PR!

**Comment by RubendeBruin** [comment]
When the outer border width is not specified then I think the border should be fragmented.

I don't think there was really a use case for the combination of outer border width and padding when I implemented it. Having it continuous would be more efficient.

**Comment by mjasperse** [comment]
Before I submit a PR, I want to check what you think of the following change to handle this combination of options:
![image](https://github.com/py-pdf/fpdf2/assets/146605/f3bc80aa-3679-4188-8b02-bc9c8b0dd501)

This adds the gutter space inside the outer border, which is compatible with how HTML renders tables with nonzero `border-spacing`.

**Comment by RubendeBruin** [comment]
My preference for this season would be:

![image](https://github.com/py-pdf/fpdf2/assets/34062862/10087e83-a569-46bb-9224-db8ad17a3334)

:-)


But for the rest of the year I think your proposal is a good one.
Just one remark/question: Is the padding supposed to be to the centerline of the border or to the edge of the border? In the picture you posted it appears to be the centerline:

<img width="606" alt="image" src="https://github.com/py-pdf/fpdf2/assets/34062862/6545054c-8b6f-4897-b55e-48a190f8cfb2">

**Comment by mjasperse** [comment]
@RubendeBruin thanks for the observation! I added a padding amount of `outer_border_width/2` so that the spacing is more consistent as you pointed out.
