### ISSUE TITLE
`KeyError: '{http://www.w3.org/2000/svg}path'` when using an svg

### ISSUE THREAD

**Issue by vadi2** [py-pdf/fpdf2#1076]
Describe the bug

**Error details**
I'm not able to use this svg that uses a <path> element which should be supported by fpdf2:

![result](https://github.com/py-pdf/fpdf2/assets/110988/e34fc067-f6f8-4043-b02d-a43358bdcb85)

**Minimal code**
Please include some minimal Python code reproducing your issue:
```python
from fpdf import FPDF

pdf = FPDF()

self.image('result.svg', x = 10, y = 8, w = 33)
```
If you don't know how to build a minimal reproducible example, please check this tutorial: https://stackoverflow.com/help/minimal-reproducible-example

**Environment**
Please provide the following information:
* **Operating System**: Debian (ChromeOS)
* **Python version**: 3.10
* **`fpdf2` version used**: 2.7.7

**Comment by Lucas-C** [comment]
Hi @vadi2

Thank you for the bug report.

You did not mention the error you got, but I guess it was something like this:
`KeyError: '{http://www.w3.org/2000/svg}path'`

I was able to identify & fix this bug in this PR:

**Comment by Lucas-C** [comment]
The fix has been merged into the `master` branch of this repo, but not released yet.

You can install this unreleased latest version this way, if you want to test that this fix solves your initial problem:

    pip install git+https://github.com/py-pdf/fpdf2.git@master

**Comment by vadi2** [comment]
Brilliant, thanks a lot! I'll try it out.

**Comment by vadi2** [comment]
The fix worked. Thank you!
