### ISSUE TITLE
No way to control line spacing inside table cell

### ISSUE THREAD

**Issue by glebarez** [py-pdf/fpdf2#1089]
Hello, I can't figure out a way to control line spacing inside table cell.
Currently the default setting is too large, and seems like a whole empty line is in between.
Is there a way to shrink it ?

## Code
```python
from fpdf import FPDF

pdf = FPDF()
pdf.add_page()
pdf.set_font("helvetica")
with pdf.table(first_row_as_headings=False) as table:
    row = table.row()
    row.cell("line1\nline2")
pdf.output("test.pdf")
```

## Result
<img width="160" alt="image" src="https://github.com/py-pdf/fpdf2/assets/47985861/ea1aff83-f5c8-463d-b6e3-86ec9fd47425">

**Comment by Lucas-C** [comment]
Hi @glebarez!

Have you checked the `line_height` setting? It's mentioned there in the docs:
* https://py-pdf.github.io/fpdf2/Tables.html#setting-row-height
* https://py-pdf.github.io/fpdf2/fpdf/table.html#fpdf.table.Table

```python
with pdf.table(first_row_as_headings=False, line_height=5) as table:
```

**Comment by glebarez** [comment]
Thanks, it worked!
