### ISSUE TITLE
How to hide 'DeprecationWarning' messages

### ISSUE THREAD

**Issue by rfc-st** [py-pdf/fpdf2#1097]
Hi!,

First and foremost: thank you for this great little wonder that allows us to _navigate_ the world of PDFs. You rock! :metal:.

**Question**: Is there any way to hide the messages relates with deprecated features. Maybe a flag or a call to a specific function?: https://imgur.com/a/QsZRI0r

Thanks!.

Best regards,

Rafa Faura

**Comment by andersonhc** [comment]
Hi @rfc-st ,

On version 2.7.6 we replaced the parameter "txt" to "text" to increase readability and maintainability of the code. 
To get rid of the warnings you can fix the parameter name on calls to `cell()`, `multi_cell()` and `write()`, like:

`pdf.multi_cell(192, 2.6, **text**=i, align='L')`

`pdf.write(h=3, **text**=prefix)`

**Comment by Lucas-C** [comment]
To add up to @andersonhc answer,
regarding warning control we some documentation there:
https://py-pdf.github.io/fpdf2/index.html#displaying-deprecation-warnings

Warnings are not displayed by default by Python.
That means that in your case, some code is invoked by `humble.py` to enable them.
You should try to figure out what library or code line in your script does that.

Finally, as [described in Python official documentation](https://docs.python.org/3/library/warnings.html),
you can reset it all and remove all rules that display warnings by calling `warnings.resetwarnings()`.

**Comment by rfc-st** [comment]
Hi,

No, nothing else: thanks to both of you for the information.

Best regards,
