### ISSUE TITLE
Incorrect type hint for OutlineSection level member

### ISSUE THREAD

**Issue by dmail00** [py-pdf/fpdf2#1112]
The level member of OutlineSection has an incorrect type hint which has been present for at least the [last three years](https://github.com/py-pdf/fpdf2/blob/f78f6851c2f20e5eeb4fe0b3690035f49477d6db/fpdf/outline.py#L14) It should be have an int type hint  from looking at [the code](https://github.com/py-pdf/fpdf2/blob/master/fpdf/outline.py#L88) and from pylance complaining about it.

**Comment by Lucas-C** [comment]
Hi @dmail00

Alright, would you like to submit a PR to fix this?

**Comment by FatimaSaleem21** [comment]
Hi @Lucas-C I would like to submit a PR for this little fix.

**Comment by Lucas-C** [comment]
> Hi @Lucas-C I would like to submit a PR for this little fix.

Awesome!

Go on 🙂

If you need help for anything, go on and ask! 😸
