### ISSUE TITLE
Multiple TExt Colors in a table cell

### ISSUE THREAD

**Issue by digitalw** [py-pdf/fpdf2#1113]
Hi,
I am trying to highlight certain parts of the text in a table cell using color (red). Is there any way of achieving this without converting the whole table to a html table and using write_html?

Thanks

**Comment by gmischler** [comment]
This is a planned feature, which I've been working at for a while now (see #339).

Unfortunately, there have been a lot of changes to the functionality of the existing table implementation. It will take some time to integrate all of those in my new version.

**Comment by Lucas-C** [comment]
Do you have any other question @digitalw or do you have you answers? 🙂

**Comment by Lucas-C** [comment]
Hi @digitalw

Unless you have more comments or questions regarding this, we will close this thread at some point.

I hope our answers helped you somehow 🙂

**Comment by Lucas-C** [comment]
Closing this now
