### ISSUE TITLE
ImportError: cannot import name 'FPDF' from 'fpdf' (unknown location)

### ISSUE THREAD

**Issue by sohyepgins** [py-pdf/fpdf2#1121]
Hi I uninstalled and reinstalled the fpdf2 multiple time but I kept on getting the following error. My python version is 3.10.13.

Describe the bug

**Error details**
Hi I uninstalled and reinstalled the fpdf2 multiple time but I kept on getting the following error. My python version is 3.10.13. Could you please help me troubleshoot?

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[2], [line 1](vscode-notebook-cell:?execution_count=2&line=1)
----> [1](vscode-notebook-cell:?execution_count=2&line=1) from fpdf import FPDF

ImportError: cannot import name 'FPDF' from 'fpdf' (unknown location)

**Minimal code**
(env-nlp) spark@RNL-MAC-16575 text-reponse-analysis-complete % python test-pdf.py
Traceback (most recent call last):
  File "/Users/spark/Documents/survey-project/text-reponse-analysis-complete/test-pdf.py", line 1, in <module>
    from fpdf import FPDF
ImportError: cannot import name 'FPDF' from 'fpdf' (unknown location)

**Comment by Lucas-C** [comment]
Hi @sohyepgins 🙂

There are a few commands you could run to help troubleshoot your problem:
```
pip --version
pip freeze  # we are only interested by the version of fpdf2 mentioned in this command output

python -m pip --version
python -m pip freeze  # we are only interested by the version of fpdf2 mentioned in this command output
```

**Comment by Lucas-C** [comment]
Given you closed this issue, I guess you solved your problem 😅
