### ISSUE TITLE
The first cell duplicates on all subsequent pages

### ISSUE THREAD

**Issue by blinking-led** [py-pdf/fpdf2#1168]
Error details

The first cell duplicates on all subsequent pages while generating pdf with tables
![table-first](https://github.com/py-pdf/fpdf2/assets/22614106/3cd085c8-720a-48c1-a3c1-71862f9e25ab)

How can I solve this issue?

Minimal code
``` python
from fpdf import FPDF
from fpdf.fonts import FontFace

pdf = FPDF()
pdf.add_page()
styleHead = FontFace(fill_color=(220, 230, 240))

with pdf.table() as table:
   row = table.row()
   row.cell("first line", style = styleHead)
   for i in range(32):
        for j in range(8):     
                row = table.row()
                row.cell(str(j))
        row = table.row()

pdf.output("unicode-.pdf")
```

Environment
Windows 10 x64
Python 3.10
fpdf2==2.7.8

I can't find any information about this issue.

**Comment by Lucas-C** [comment]
Hi @blinking-led

This is actually a **feature** 😄

A request was made very recently to disable this, in https://github.com/py-pdf/fpdf2/issues/1151
As you can read in this issue, this has been implemented; but is not released yet.
You can still test it by installing `fpdf2` from git, as mentioned in my last comment, and you can read the relevant documentation there: https://py-pdf.github.io/fpdf2/Tables.html#disable-table-headings

Does this answer your question @blinking-led?

**Comment by Lucas-C** [comment]
My pleasure 🙂

FYI, this has been released last week: https://github.com/py-pdf/fpdf2/releases/tag/2.7.9
