### ISSUE TITLE
Unspecific Errors from Pipeline

### ISSUE THREAD

**Issue by gmischler** [py-pdf/fpdf2#1178]
When something fails in the checking pipeline for a PR, then recently the error message from the respective subprocess isn't displayed anymore. All we get to see is eg. this:
![grafik](https://github.com/py-pdf/fpdf2/assets/17468844/12292cde-9487-4444-8e52-7c817f1a4a3d)
Where currently there is only a lonely "`Error:`" now, there used to be the full stderr output of the failing check.
What has changed here?
Is this a deliberate change?
Can it be fixed please?

As a reviewer, the current lack of detail information makes it rather hard to give useful advice. Unfortunately I'm not familiar enough with the pipeline mechanics to fix it myself...

**Comment by Lucas-C** [comment]
I'm sorry but I do not reproduced your problem... 😞

The last failing GitHub Actions execution is this one: https://github.com/py-pdf/fpdf2/actions/runs/9155251026/job/25201525486

The failure gets displayed this way in my Firefox browser on Windows:
![Capture d'écran 2024-05-23 131544](https://github.com/py-pdf/fpdf2/assets/925560/f00cc44d-1946-4303-8927-f4645512946d)

Do you see the same thing?

Could you please provide a link to job where the problem occurs?

**Comment by gmischler** [comment]
My screenshot was from #1176, which shows a full error message now.

If you didn't change anything in the pipeline, then I guess it was a hickup on githubs side, which is fixed now.

**Comment by Lucas-C** [comment]
Yes, I think that you are right!

In my experience, sometimes reloading the jobs log page can help to resolve some display issues.
