### ISSUE TITLE
Add Cell Level Controll for Table Borders

### ISSUE THREAD

**Issue by bbrenter** [py-pdf/fpdf2#1192]
**Intent**
It would be great to have control over table borders by defining them for each cell.

**Describe the solution you'd like**
This could for example be implemented by adding the border string slot to the Cell Class and use it inside the get_cell_border function to determine the border for each cell. A possible implementation could look like this...

![image](https://github.com/py-pdf/fpdf2/assets/88101215/024cfbd7-440d-4c27-aaef-753a584bf559)

![image](https://github.com/py-pdf/fpdf2/assets/88101215/f6c2e6e1-14d6-4700-b2b1-f5f1203f22f6)

![image](https://github.com/py-pdf/fpdf2/assets/88101215/164b6858-79d6-49ab-b5a7-d793bef24080)

**Comment by Kaustbh** [comment]
Hi  I'm new to open source, but I'm eager to dive in and help out. I came across this issue and I think I can tackle it. Can I work on it?

**Comment by Lucas-C** [comment]
Yes, given the history on this issue, you are very welcome to tackle this @Kaustbh 🙂

As a minor change to the interface suggested by @bbrenter,
I think it would be better if the new `border` property of [Cell](https://py-pdf.github.io/fpdf2/fpdf/table.html#fpdf.table.Cell) was typed with a new subclass of [CoerciveEnum](https://py-pdf.github.io/fpdf2/fpdf/enums.html#fpdf.enums.CoerciveEnum), maybe named `CellBordersLayout` (in a similar fashion as [TableBordersLayout](https://py-pdf.github.io/fpdf2/fpdf/enums.html#fpdf.enums.TableBordersLayout)). It could have those values:
* `NONE` = 0
* `LEFT` = 1
* `RIGHT` = 2
* `TOP` = 4
* `BOTTOM` = 8
* `ALL` = `LEFT | RIGHT | TOP | BOTTOM = 15`
* `INHERIT` = 16 would be the default value, meaning to inherit from the table layout scheme

A starting point for you @Kaustbh could to be to read our [development guidelines](https://py-pdf.github.io/fpdf2/Development.html).

Then, you could add a new unit test to `test/table/test_table.py`.

Please ask away if you have any question! 🙂

**Comment by Kaustbh** [comment]
Hi @Lucas-C , 

I'm currently working on implementing the `CellBordersLayout` as suggested. However, I'm having trouble understanding  table rendering logic and `get_cell_border` function, could you please help me?

**Comment by Kaustbh** [comment]
I understood the logic of rendering and get_cell_border function, can you please tell me how should I write ```CellBordersLayout```  class whether it should be of type ```CoerciveEnum``` or ```CoerciveIntFlag``` ?

**Comment by Kaustbh** [comment]
Please reply on how I should implement `CellBordersLayout`.

**Comment by andersonhc** [comment]
Hi @Kaustbh ,

The CellBordersLayout enum could be a good use case for CoerciveIntFlag if it wasn't for the `INHERIT` option. `INHERIT` can't be combined with the other values, so I believe CoerciveEnum is your better option.

**Comment by Kaustbh** [comment]
But `Enum` does not support bitwise operations, which we can do using `IntFlag` , and please also tell me what should be the input format to the new border parameter in `cell()` function?

**Comment by Kaustbh** [comment]
@Lucas-C  can you please tell me the right way to do it?

**Comment by Lucas-C** [comment]
Hi @Kaustbh

A quick test revealed that with `CoerciveIntFlag` as a parent classe it works fine:
```python
class CellBordersLayout(CoerciveIntFlag):
    NONE = 0
    LEFT = 1
    RIGHT = 2
    TOP = 4
    BOTTOM = 8
    ALL = 15
    INHERIT = 16

    @classmethod
    def coerce(cls, value):
        if isinstance(value, int) and value > 16:
            raise ValueError("INHERIT cannot be combined with other values")
        return super(cls, cls).coerce(value)

print(CellBordersLayout.NONE)
print(CellBordersLayout.BOTTOM)
print(CellBordersLayout.INHERIT)
print(CellBordersLayout.ALL)
print(CellBordersLayout.LEFT | CellBordersLayout.RIGHT | CellBordersLayout.TOP | CellBordersLayout.BOTTOM)
print(CellBordersLayout.coerce(12))
print(CellBordersLayout.NONE | 1)
print(CellBordersLayout.coerce(17))
print(CellBordersLayout.INHERIT | 1)  # <- this should also raise an error
```

**Comment by Lucas-C** [comment]
Hi @Kaustbh

Does my last answer helps you to move forward on this implementation?
Do you have other questions?
Do you plan to continue working on this issue?

**Comment by Kaustbh** [comment]
Yes, I am working on this issue, and yes your last answer helped me move forward.

**Comment by Lucas-C** [comment]
> Yes, I am working on this issue, and yes your last answer helped me move forward.

Great 🙂

I'm assigning this issue to you then!

**Comment by Lucas-C** [comment]
This feature has been included in the new release published today:
https://github.com/py-pdf/fpdf2/releases/tag/2.8.2
