### ISSUE TITLE
Line spacing for a long line that is displayed in several lines.

### ISSUE THREAD

**Issue by rfc-st** [py-pdf/fpdf2#1213]
Hello!,

First of all, thank you for this library ^^.

Is there any parameter, or configuration option, to define the spacing for a long line of text that is displayed in several lines?.

As you can see in the following image (https://imgur.com/a/y8X088R), the fourth line starting with "Nota : " is displayed in two lines ... without any vertical spacing between them; both lines are displayed too close together.

Thanks!

**Comment by andersonhc** [comment]
> Hello!,
> 
> First of all, thank you for this library ^^.
> 
> Is there any parameter, or configuration option, to define the spacing for a long line of text that is displayed in several lines?.
> 
> As you can see in the following image (https://imgur.com/a/y8X088R), the fourth line starting with "Nota : " is displayed in two lines ... without any vertical spacing between them; both lines are displayed too close together.
> 
> Thanks!

You can set the spacing with the [parameter "h"](https://github.com/py-pdf/fpdf2/blob/d574b0796d5f64aade3a6051554fe6708e2e320a/fpdf/fpdf.py#L3677). The default value of this parameter is the font size in pt.

**Comment by Lucas-C** [comment]
Hi @rfc-st, and thank you for your kind words!

As a complementary answer, if you are using [the multi_cell() method](https://py-pdf.github.io/fpdf2/fpdf/fpdf.html#fpdf.fpdf.FPDF.multi_cell), you can also play with the `max_line_height` parameter.

**Comment by Lucas-C** [comment]
Also, a side question: do you see a place in our documentation where we should document this better? 😅

**Comment by rfc-st** [comment]
Hello,

Thanks to both of you for the advices!: I will try them this weekend. And about the documentation, if you don't mind leaving this issue open for a few more days, I will check it thoroughly. I'm sure your advice is indicated.

Best regards,

**Comment by rfc-st** [comment]
Hello,

I have succeeded, by using YPos! (https://py-pdf.github.io/fpdf2/fpdf/fpdf.html#fpdf.fpdf.YPos): 

https://imgur.com/a/DaPtwtq

Thanks for your advices and for this great library!.

Regards,
