### ISSUE TITLE
Text columns issue with top margin

### ISSUE THREAD

**Issue by andersonhc** [py-pdf/fpdf2#1214]
I ran in a problem with text columns where when a paragraph starts at the bottom of a column and it has a top margin that should push the text to the next column, it causes a page break and stay on the same column.

This is a simple example:

```python
from fpdf import FPDF

LOREM_IPSUM = "Lorem ipsum Ut nostrud irure reprehenderit anim nostrud dolore sed ut Excepteur dolore ut sunt irure consectetur tempor eu tempor nostrud dolore " * 12

pdf = FPDF()
pdf.add_page()
pdf.set_font("Helvetica", "", 14)


with pdf.text_columns(text_align="J", ncols=2) as cols:
    for _ in range(3):
        with cols.paragraph(
            text_align="J",
            bottom_margin=pdf.font_size * 5,
            top_margin = pdf.font_size * 5,
        ) as par:
            par.write(text=LOREM_IPSUM)
        
pdf.output("text-region-cols.pdf")
```

I believe the problem is in [TextRegion._render_column_lines](https://github.com/py-pdf/fpdf2/blob/d574b0796d5f64aade3a6051554fe6708e2e320a/fpdf/text_region.py#L519-L530), the code that detects pdf.y surpassing bottom is in a else statement and never executed when top margin is added.

@gmischler do you think there is any possible side effect removing the `else` from line 527 and de-indenting the 3 lines under it?

**Comment by gmischler** [comment]
> @gmischler do you think there is any possible side effect removing the else from line 527 and de-indenting the 3 lines under it?

An interesting corner case, thanks for catching that!
Your suggested solution looks reasonable at first glance.
But it may be worth to also check if paragraph top margins are correctly taken into account in other places, like eg. the calculation to determine the total height required by the text on [line 676](https://github.com/py-pdf/fpdf2/blob/d574b0796d5f64aade3a6051554fe6708e2e320a/fpdf/text_region.py#L676).
I can take a closer look at it later this week.
