### ISSUE TITLE
Stampapdf

### ISSUE THREAD

**Issue by Gae58** [py-pdf/fpdf2#1227]
Hi I just installed the library and am doing some testing. I started with the code proposed by the application but it returns this error
ValueError at /printIscr/5/pdf/.

Pale.views.Pale.Tables.AssociatedViews.PrintIscr did not return an HttpResponse object. Instead, it returned None.

Request method: GET
Request URL: http://127.0.0.1:8000/stampaIscr/5/pdf/
Django version: 5.0.1
Exception type: ValueError
Exception value: 	

Pale.views.Pale.Tables.AssociatedViews.PrintIscr did not return an HttpResponse object. Instead, it returned None.

Exception location: C:\ProjectsPython\PalestraGesvenv\Libsite-packages\django\corehandlers\base.py, line 332, in check_response
Lifted during: Pale.views.Pale.Tables.AssociatedViews.PrintIscr
Python executable: C:\ProjectsPython\PalestraGes\venv\Scripts\python.exe
Python version: 3.12.0
Python path: 	

['C:\ProjectsPython\PalestraGes',
 'C:´Users'Gaetano´AppData´Local'Programs'Python'Python'Python312´Python312.zipper',
 'C:´Users'Gaetano´AppData´Local'Programs'Python'Python312´DLLs',
 'C:´Users'Gaetano´AppData´Local'Programs'Python'Python312´Lib',
 'C:´Users'Gaetano´AppData´Local'Programs'Python'Python312',
 'C:´Python Projects´´ GymGes´´venv',
 'C:\ProjectsPython\PalestraGes\venv\Lib\site-packages']

Server time: Wed, 17 Jul 2024 17:02:34 +0200

I also tried return response and httpResponse but it returns more errors,
what am I doing wrong?
Sorry for not posting

**Comment by gmischler** [comment]
Hello @Gae58 ,

can you please explain why you think your problem is related to the **fpdf2** library?
I don't see any indication in your post that you're even using it.

**Comment by Gae58** [comment]
sorry I didn't understand that the reports are only for anomalies and not
for siegations

Il giorno mer 17 lug 2024 alle ore 21:38 Georg Mischler <
***@***.***> ha scritto:
