### ISSUE TITLE
Problem setting fallback font

### ISSUE THREAD

**Issue by munlicode** [py-pdf/fpdf2#1238]
Hi there!
I was trying to set fallback font to be able to handle math symbols using NotoSansMath, but I got an error.

Code:
from fpdf import FPDF

text = 'Enter equations: 4*x*pi + 2*i/2, e^{iπ} + 1 = 0'

pdf = FPDF()
pdf.add_page()

#Add the custom font
pdf.add_font('notomath', '', r'C:\Users\Windows\Fonts\NotoSansMath-Regular.ttf')
#set times as main font
pdf.set_font('times', '', 12)
#set fallback font
pdf.set_fallback_fonts('notomath')
pdf.cell(0, 10, text)
pdf.output('example.pdf')

Output:

  File "c:\Users\diff.py", line 13, in <module>
    pdf.set_fallback_fonts('notomath')
  File "C:\Users\site-packages\fpdf\fpdf.py", line 2031, in set_fallback_fonts
    raise FPDFException(
fpdf.errors.FPDFException: Undefined fallback font: n - Use FPDF.add_font() beforehand

**Comment by andersonhc** [comment]
Hi @munlicode,
I guess you found the problem as you closed the issue - set_fallback_font() expects a list, so you need to pass `set_fallback_font(['notomath'])`.
You should also use a TTF font as your main set font for fallback to work properly.

**Comment by munlicode** [comment]
yeah, you are right


> Hi @munlicode, I guess you found the problem as you closed the issue - set_fallback_font() expects a list, so you need to pass `set_fallback_font(['notomath'])`. You should also use a TTF font as your main set font for fallback to work properly.
