### ISSUE TITLE
Text shaping does not work with `text()`

### ISSUE THREAD

**Issue by bmiklautz** [py-pdf/fpdf2#1265]
When using `text()` with shaping enabled like documented in 
https://py-pdf.github.io/fpdf2/Text.html  and https://py-pdf.github.io/fpdf2/TextShaping.html the created text isn't shaped.

**Minimal code**

```python
from fpdf import FPDF

pdf = FPDF()
pdf.add_page()
pdf.add_font('khmer', '', 'NotoSansKhmer-Regular.ttf')
pdf.set_font('khmer', size=32)
pdf.set_text_shaping(True)
pdf.text(20,100, text="ភាសាខ្មែរ")

pdf.set_xy(20,110)
pdf.cell(text="ភាសាខ្មែរ")

pdf.set_xy(20,130)
pdf.write(None, text="ភាសាខ្មែរ")

pdf.output("hello_world.pdf")
```
In the example Noto Sans Khmer was used (can be downloaded from https://fonts.google.com/noto/specimen/Noto+Sans+Khmer) but the problem occurs with other fonts as well.

The following screenshot shows the output of the example. Text placed with `write()` and `cell()` is represented correctly but `text()` (first line)  isn't. 
![Screenshot 2024-09-20 at 12 19 23](https://github.com/user-attachments/assets/d9633887-76c3-405e-b693-ec3b3e8ef729)

**Environment**
Please provide the following information:
* **Operating System**: MacOS, Linux (Debian/Ubuntu)
* **Python version**:  Python 3.10.14, Python 3.11.9, Python 3.12.4
* **`fpdf2` version used**: master 90c7d7f8780ff524a469fb7deff4dffb88be3a5f

Thank you for your efforts and work on fpdf2.

**Comment by andersonhc** [comment]
Hi @bmiklautz,

The `text()` method is kept on the codebase for backwards compatibility, but it lacks many of the features available in `write()`, `cell()`, and `multicell()` like markdown and text shaping.

We could definitely add this information on our documentation to avoid confusion. Let me know if you're interested in submitting a PR.

**Comment by bmiklautz** [comment]
@andersonhc thank you for your answer. I've created #1265.
