### ISSUE TITLE
Add support for LZWDecode compression

### ISSUE THREAD

**Issue by Lucas-C** [py-pdf/fpdf2#1271]
**Please explain your intent**
Currently `fpdf2` supports 4 compression methods for images:
https://github.com/py-pdf/fpdf2/blob/2.8.0/fpdf/image_parsing.py#L35

The PDF standard specification (_cf._ [PDF32000_2008.pdf section 7.4 Filters](https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/PDF32000_2008.pdf)) defines several other compression filters, including `LZWDecode`.

Recently, this filter was implemented by @MartinThoma in our companion library `pypdf`: https://github.com/py-pdf/pypdf/pull/2883

**Describe the solution you'd like**
Support `LZWDecode` for images compression.

**Comment by opposss** [comment]
Hi!

I'd love to work on this issue can you assign me?

**Comment by Lucas-C** [comment]
Sure, done!

**Comment by Lucas-C** [comment]
Hi @opposss

Have you been able to start working on this implementation?
Do you have any questions?

**Comment by opposss** [comment]
Hi @Lucas-C 

Almost done, I will send the PR for review soon.
Before that I would like to ask 2 questions:

1) Do I understand correctly that I can completely use the code that was written by @MartinThoma ?

2) Should I add logic to use the LZW filter in case of GIF images or other image formats?

**Comment by Lucas-C** [comment]
This was implemented by @opposss in PR https://github.com/py-pdf/fpdf2/pull/1286

**Comment by Lucas-C** [comment]
This feature has been included in the new release published today:
https://github.com/py-pdf/fpdf2/releases/tag/2.8.2
