### ISSUE TITLE
font sizing behavior changed for local_context

### ISSUE THREAD

**Issue by beldaz** [py-pdf/fpdf2#1275]
The new behaviour of local_context in release 2.8.1 differs from 2.7.9, in that providing `font_size` was handled the same way as in `set_font()` and `set_font_size()` and assumed to be in points. Now it appears to be treated as the page units.

**Minimal code**

```python
from fpdf import FPDF, FPDF_VERSION

pdf = FPDF(unit="mm")
pdf.add_page()

EXAMPLE_FONT_SIZE = 9
WIDTH = 200
HEIGHT = 10
pdf.set_font("helvetica", size=EXAMPLE_FONT_SIZE)

pdf.cell(
    WIDTH,
    HEIGHT,
    "This is sized with set_font",
    new_x="LMARGIN",
    new_y="NEXT",
    align="C",
)

pdf.set_font_size(EXAMPLE_FONT_SIZE)

pdf.cell(
    WIDTH,
    HEIGHT,
    "This is sized with set_font_size",
    new_x="LMARGIN",
    new_y="NEXT",
    align="C",
)

with pdf.local_context(
    font_size=EXAMPLE_FONT_SIZE,
):
    pdf.cell(
        WIDTH,
        HEIGHT,
        "This is sized with local_context",
        new_x="LMARGIN",
        new_y="NEXT",
        align="C",
    )

pdf.output(f"local_context_example{FPDF_VERSION.replace(".", "_")}.pdf")
```

**Environment**
* **Operating System**: Mac OSX
* **Python version**: 3.12.6
* **`fpdf2` version used**: 2.8.1

This change appears to have been introduced in https://github.com/py-pdf/fpdf2/pull/1209

In 2.7.9 (and before, presumably) the text in all three lines is printed at the same size. See the attached [local_context_example_2_7_9.pdf](https://github.com/user-attachments/files/17284936/local_context_example_2_7_9.pdf) rendered example using version 2.7.9, compared to 
[local_context_example2_8_1.pdf](https://github.com/user-attachments/files/17284938/local_context_example2_8_1.pdf) using 2.8.1.

**Comment by Lucas-C** [comment]
Thank you @beldaz for this bug report.

I can confirm that this is indeed a regression compared with `fpdf2` 2.7.9

I will try to investigate this asap.

@allcontributors please add @beldaz for bug

**Comment by Lucas-C** [comment]
I was able to recall the reason for this change: [`FPDF.local_context()`](https://py-pdf.github.io/fpdf2/fpdf/fpdf.html#fpdf.fpdf.FPDF.local_context) used to treat `font_size` as a value in points. Now this is the role of `font_size_pt`, whereas `font_size` allows to set the font size into chosen document units (specified with `FPDF(unit=)`) - MR: [#1207]([https://github.com/py-pdf/fpdf2/pulls/1207](https://github.com/py-pdf/fpdf2/pulls/1207?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen))

I opened PR https://github.com/py-pdf/fpdf2/pull/1278 to document this.

**Comment by Lucas-C** [comment]
@beldaz : can you solve your issue by either:
* passing `unit="pt"` to `FPDF` constructor
* * using `font_size_pt` instead of `font_size`?

**Comment by beldaz** [comment]
@Lucas-C thanks for the clarification. I can certainly work around the issue. Considering your suggested workarounds:
* My code allows the user to choose their preferred units (usually mm or inches) so fixing them to pts would not be appropriate in my particular case;
* using `font_size_pt` is probably the best way - I can add a shim to use `font_size_pt` for versions>=2.8.1, otherwise `font_size`.

Personally, I would prefer the change in behaviour to be reversed, though I understand that you may have better reasons to keep it. To my knowledge, `local_context()` is the only place where font size is not handled in units on points, which is the native sizing of fonts in all software tools I use. If it really is necessary to supply sizes in page units, an alternative would be to cater to that as the special case with, e.g., `font_size_page_units`.

This is all minor stuff. I can work around whatever you choose. I am very happy that this package exists at all, and I greatly appreciate your work to maintain it.

**Comment by Lucas-C** [comment]
> To my knowledge, `local_context()` is the only place where font size is not handled in units on points, which is the native sizing of fonts in all software tools I use.

`FPDF.local_context()` allows both units!
You can just specify `font_size_pt` 🙂
