### ISSUE TITLE
writehtml Turkish Character Error

### ISSUE THREAD

**Issue by mglnr** [py-pdf/fpdf2#1281]
Hello,

I'm testing with writehtml at https://py-pdf.github.io/fpdf2/HTML.html. Unfortunately, I could not run the application when I used Turkish characters in my test. The application does not open when you type the characters "ğĞİÖÖüÜ". I added add_font with external Turkish character support, but the problem persists.

**Comment by Lucas-C** [comment]
Hi @mglnr

I'd be happy to try to help you, but the information you provided is not precise enough to be able to solve your problem.

Could you please provide some **minimal code reproducing your problem**: https://stackoverflow.com/help/minimal-reproducible-example

Also, what do you mean by _"The application does not open"_?

Do you get an error when running your Python script?

Or is it that you cannot open the PDF file produced?

At this point, I can only guess that the font file you provided (the _"external Turkish character support"_) simply does not render the characters `ğĞİÖÖüÜ`

**Comment by mglnr** [comment]
Thank you for your interest. When I type one of the characters "ğĞİÖÖÜÜ" and run my test application, the application closes without creating the pdf. When I use only the characters I specified, the situation I specified occurs.

**Comment by Lucas-C** [comment]
> When I type one of the characters "ğĞİÖÖÜÜ" and run my test application, the application closes without creating the pdf.

Do you have any error produced?

If the call to `.output()` fails to create a file, you should probably have an error raised.

If so, could you please share the stacktrace?

Otherwise there is really not much I can do to help you...

**Comment by andersonhc** [comment]
@mglnr Here is a small test I did showing fpdf2 can handle the characters if you are using a compatible font:

```python
from fpdf import FPDF

pdf = FPDF()
pdf.add_page()
pdf.add_font(family="Noto", fname="NotoSans-Regular.ttf")
pdf.set_font("Noto", "", 16)
pdf.write_html("""
  <h1>ğĞİÖÖÜÜ</h1>
""")
pdf.output("issue1281.pdf")
```

I really don't know how to help you any further without specific information about your code and the error you are getting.

**Comment by mglnr** [comment]
> @mglnr Here is a small test I did showing fpdf2 can handle the characters if you are using a compatible font:
> 
> ```python
> from fpdf import FPDF
> 
> pdf = FPDF()
> pdf.add_page()
> pdf.add_font(family="Noto", fname="NotoSans-Regular.ttf")
> pdf.set_font("Noto", "", 16)
> pdf.write_html("""
>   <h1>ğĞİÖÖÜÜ</h1>
> """)
> pdf.output("issue1281.pdf")
> ```
> 
> I really don't know how to help you any further without specific information about your code and the error you are getting.

> pdf.add_font(family="Noto", fname="NotoSans-Regular.ttf")
> pdf.set_font("Noto", "", 16)


> ```python
>     <table width="50%" border="1">
>       <thead>
>         <tr>
>           <th width="30%">ID</th>
>           <th width="70%">Name</th>
>         </tr>
>       </thead>
>       <tbody>
>         <tr>
>           <td>1</td>
>           <td>Alice</td>
>         </tr>
>         <tr>
>           <td>2</td>
>           <td>Bob</td>
>         </tr>
>       </tbody>
>     </table>
> ```

Thank you for your interest. When I changed the family to times-roman in the code you gave, the Turkish characters worked, but when I wrote the html table code below it, it did not work. Sample code:

```python
from fpdf import FPDF

pdf = FPDF()
pdf.add_page()
pdf.add_font(family="Times-Roman", fname="times.ttf")
pdf.set_font("Times-Roman", "", 12)
pdf.write_html("""
  <p align="justify"> deneme deneme </p>
    <table width="50%" border="1">
      <thead>
        <tr>
          <th width="30%">ID</th>
          <th width="70%">Name</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>1</td>
          <td>Alice</td>
        </tr>
        <tr>
          <td>2</td>
          <td>Bob</td>
        </tr>
      </tbody>
    </table>
""")
pdf.output("html.pdf")

input("Pencereyi kapatma.")
```

**Comment by mglnr** [comment]
> The default is table header being in bold and your code is failing because you didn't add a bold version of the font.
> 
> Add this line and your code should run OK:
> 
> ```python
> pdf.add_font(family="Times-Roman", style="B", fname="timesbd.ttf")
> ```

Thank you. I missed that detail.

**Comment by Lucas-C** [comment]
Do you have any more questions, or can this issue be closed? 🙂
