### ISSUE TITLE
{nb} text shaping breakage can't be worked around anymore

### ISSUE THREAD

**Issue by philj56** [py-pdf/fpdf2#1287]
Related to #1090:

In fpdf2 2.7.7, it was possible to work around text shaping breaking `{nb}` by temporarily disabling it (as is done in the example in #1090). From 2.7.8 onwards, this is no longer possible; enabling text shaping once breaks all subsequent `{nb}`s, even if it is disabled again.

Minimal example:
```python
from fpdf import FPDF

pdf = FPDF()
pdf.add_font('mulish', style='', fname='mulish-regular.ttf')
pdf.add_page()
pdf.set_font('mulish', '', 24)
pdf.write(text='Pages {nb}')
pdf.ln()
pdf.set_text_shaping(True)
pdf.write(text='Pages {nb}')
pdf.ln()
pdf.set_text_shaping(False)
pdf.write(text='Pages {nb}')
pdf.output('test.pdf')
```

With fpdf2 2.7.7:
![before](https://github.com/user-attachments/assets/3743e359-0aa0-46d8-88b8-9f8e98b286ce)

With fpdf2 2.7.8+:
![after](https://github.com/user-attachments/assets/c7894ab0-5747-492b-9800-7b5fe9c25d67)

**Comment by philj56** [comment]
Hi @Lucas-C,

It's a known limitation, but you used to still be able to get page numbers to work by temporarily disabling text shaping just for the page number, then re-enabling it. This is no longer possible, so it seems like something else has changed internally and this might be a different issue like, something like text shaping not being disabled when expected. (e.g. the example code given in #1090 no longer produces the same output).

I think the information here is useful in addition to that in #1090, but I'm happy for them to be merged / handled however you see fit.

**Comment by Lucas-C** [comment]
You are right @philj56, the problem is elswewhere.

I think I found the issue & fixed it in PR https://github.com/py-pdf/fpdf2/pull/1288

@allcontributors please add @philj56 for bug

**Comment by philj56** [comment]
That's great, thanks for the quick reply and fix!

**Comment by Lucas-C** [comment]
@philj56 Could you please test if this issue is solved for you using the latest version of `fpdf2` from `git`?

You can install it with: `pip install git+https://github.com/py-pdf/fpdf2.git@master`

**Comment by philj56** [comment]
@Lucas-C Yup, that seems to be working fine now, thanks!

**Comment by Lucas-C** [comment]
Thank you for testing 👍

**Comment by Lucas-C** [comment]
This fixup has been included in the new release published today:
https://github.com/py-pdf/fpdf2/releases/tag/2.8.2
