### ISSUE TITLE
HTML table with null text in span cells that don't show correctly

### ISSUE THREAD

**Issue by whoisltd** [py-pdf/fpdf2#1293]
Describe the bug:

the HTML table with null text in span cells that don't show correctly
HTML table with `td` tag have `rowspan`, `colspan` > 1 and text inside is null the pdf output not show table correctly

HTML input:

```html
<table border="1">
    <tr>
        <td rowspan=2></td>
        <td>cell 2</td>
        <td>cell 3</td>
    </tr>
    <tr>
        <td>cell 4</td>
        <td>cell 5</td>
    </tr>
    <tr>
        <td colspan=2></td>
        <td>cell 7</td>
    </tr>
</table>
```
Expect output:
![image](https://github.com/user-attachments/assets/df83a661-751f-4322-85c1-2a2dec44053f)
Actual ouput:
![image](https://github.com/user-attachments/assets/cacf2098-490b-49f5-bc40-99e25dc8a765)

**Error details**
the HTML table with null text in span cells that don't show correctly

**Minimal code**
```python
from fpdf import FPDF

pdf = FPDF()
pdf.add_page()
pdf.write_html(
    """<table border="1">
    <tr>
        <td rowspan=2></td>
        <td>cell 2</td>
        <td>cell 3</td>
    </tr>
    <tr>
        <td>cell 4</td>
        <td>cell 5</td>
    </tr>
    <tr>
        <td colspan=2></td>
        <td>cell 7</td>
    </tr>
</table>
    """,
    table_line_separators=True,
)
pdf.output("output.pdf")
```
**Environment**
Please provide the following information:
* **Operating System**: Ubuntu 24.04
* **Python version**: 3.8.16
* **`fpdf2` version used**: 2.8.1

**Comment by Lucas-C** [comment]
Thank you for the report @whoisltd 👍

@allcontributors please add @whoisltd for bug and code

**Comment by Lucas-C** [comment]
This fixup has been included in the new release published today:
https://github.com/py-pdf/fpdf2/releases/tag/2.8.2
