### ISSUE TITLE
Syntax error in fonts.py

### ISSUE THREAD

**Issue by iparfitt** [py-pdf/fpdf2#1296]
Running fpdf2 version 2.8.1,  in an import step:

` from fpdf import Align, FontFace, FPDF, outline`

I get a syntax error: `SyntaxError: invalid syntax` that says it's coming from fonts.py on line 150

**Comment by iparfitt** [comment]
I didn't have this issue with 2.7.9

**Comment by Lucas-C** [comment]
Hi @iparfitt

I'd be happy yo try to help 🙂

Could you please provide the following information:

* what OS are you using? Windows, Linux, MaxOSX...

* what version of Python & `pip` are you using? You can run: `python --version`, `pip --version`

* what version of `fpdf2` and/or `fpdf` are you using? Given your message, I guess that your are using `fpdf2` 2.8.1, but there could also a version of the old `fpdf` package installed in your environment. Could you run `pip freeze` and check what versions of `fpdf2` & `fpdf` appear? (or even simpler on Linux: `pip freeze | grep fpdf`)

* Finally, could you please run: `python -c "from fpdf import FPDF_VERSION; print(FPDF_VERSION)"`

**Comment by iparfitt** [comment]
Hey @Lucas-C 

I'm currently using it on Linux, with Python 3.7.5 and pip 24.0. I definitely only have fpdf2 version 2.8.1 installed and that last command is printing the following:
`#14 [analysis  8/12] RUN python3 -c "from fpdf import FPDF_VERSION; print(FPDF_VERSION)"
#14 0.625 Traceback (most recent call last):
#14 0.625   File "<string>", line 1, in <module>
#14 0.625   File "/usr/local/lib/python3.7/dist-packages/fpdf/__init__.py", line 22, in <module>
#14 0.625     from .fpdf import (
#14 0.625   File "/usr/local/lib/python3.7/dist-packages/fpdf/fpdf.py", line 88, in <module>
#14 0.625     from .fonts import CoreFont, CORE_FONTS, FontFace, TextStyle, TitleStyle, TTFFont
#14 0.625   File "/usr/local/lib/python3.7/dist-packages/fpdf/fonts.py", line 150
#14 0.625     /,
#14 0.625     ^
#14 0.625 SyntaxError: invalid syntax
#14 ERROR: process "/bin/sh -c python3 -c \"from fpdf import FPDF_VERSION; print(FPDF_VERSION)\"" did not complete successfully: exit code: 1`

**Comment by andersonhc** [comment]
The slash to force positional only parameters was [introduced on python 3.8](https://docs.python.org/3.8/whatsnew/3.8.html#positional-only-parameters), that's definitely why you are getting this error on python 3.7.

Python 3.7 reached [end-of-life](https://devguide.python.org/versions/#supported-versions) over a year ago and is not receiving even security upgrades. Do you need to keep python on an outdated version?

**Comment by GammaGames** [comment]
If you're going to break support for 3.7 you should at least remove it from the supported versions

**Comment by GammaGames** [comment]
Include a note in the changelog too

**Comment by Lucas-C** [comment]
> If you're going to break support for 3.7 you should at least remove it from the supported versions
> Include a note in the changelog too

You are entirely right @GammaGames, I agree with you.

We effectively removed support for Python 3.7 a year ago, due to our underlying dependency to `fonttools`:
https://github.com/py-pdf/fpdf2/pull/1025

But we should indeed better communicate about this:
* in `CHANGELOG.md`
* in `setup.cfg`
* in `tox.ini`
* in `README.md`
* in `docs/index.md`

I'm assigning this task to myself

**Comment by Lucas-C** [comment]
I opened PR https://github.com/py-pdf/fpdf2/pull/1299

@andersonhc : could you please review it? 🙂 🙌
