### ISSUE TITLE
The default underlines of link (<a>) tags continue past the link into the remainder of the sentence.

### ISSUE THREAD

**Issue by DerekRobin** [py-pdf/fpdf2#1311]
When creating a link using an `<a></a>` tag and `pdf.write_html()`, the underline which normally appears on links continues past the link and throughout the remainder of the sentence.

**Error details**
No exceptions are raised

**Minimal code**
```python
from fpdf import FPDF
pdf = FPDF()
pdf.add_page()
pdf.write_html(
    """
    The default <a href="https://www.google.com/" target="_blank">link underline</a> continues past the end of the link.
    """
)
pdf.write_html(
    """
    <a href="https://www.google.com/" target="_blank">It also occurs</a> when the link starts the sentence.
    """
)
pdf.output("link.pdf")
```
**Screenshot of output PDF**
![link.pdf](https://github.com/user-attachments/assets/8fc01141-ed4d-499a-a054-63e4490528ea)

**Environment**
Please provide the following information:
* **Operating System**: Ubuntu 22.04.1 LTS
* **Python version**:Python 3.10.8
* **`fpdf2` version used**: Unreleased version @ git+https://github.com/py-pdf/fpdf2.git@fb1b01d9113e7b8326f9d12491679b5c52f734d3

**Comment by K-Hern** [comment]
Hello! I am looking into this. Could I be assigned?

**Comment by Lucas-C** [comment]
Sure, @andersonhc assigned you this issue 🙂

If you have any question, go on and ask!

A good starting point can be: https://py-pdf.github.io/fpdf2/Development.html

**Comment by K-Hern** [comment]
Thank you for the guidance! I believe I have found and fixed the issue! I have submitted a PR.

**Comment by Lucas-C** [comment]
I have just merged PR https://github.com/py-pdf/fpdf2/pull/1316 that fixed this issue.

**Comment by dhruvshah-commvault** [comment]
When will this fix be released?

**Comment by Dvidian** [comment]
When will this fix be released?

**Comment by Lucas-C** [comment]
Hi @Dividan

I plan to perform a new release during this month (april 2025).

I want to continue working on PR https://github.com/py-pdf/fpdf2/pull/1387 and maybe merge it before the next release.

**Comment by Dvidian** [comment]
Thank you

**Comment by Lucas-C** [comment]
Released now in https://github.com/py-pdf/fpdf2/releases/tag/2.8.3
