### ISSUE TITLE
Inline SVG

### ISSUE THREAD

**Issue by dirk-bremen** [py-pdf/fpdf2#1328]
Hi,

is there a way I can use SVG syntax to generate a SVG in python without importing an image?

I have a workaround to write a text file as temp.svg and import temp.svg as an image and delete the file.
But I would like to avoid saving and deleting a file and create an svg image on the fly.

Thank you

**Comment by andersonhc** [comment]
You can use BytesIO

```python
from io import BytesIO

bio = BytesIO(my_svg)
bio.seek(0)

fpdf.image(bio)
```

**Comment by dirk-bremen** [comment]
Thank you!!! Cool.
