### ISSUE TITLE
Right-aligned HTML paragraph breaks inline font styling

### ISSUE THREAD

**Issue by boghison** [py-pdf/fpdf2#151]
Bold/italic/underline text in `p` tags works for default parameters, but setting `align="right"` breaks the layout:
<img width="571" alt="Screen Shot 2021-05-29 at 18 07 41" src="https://user-images.githubusercontent.com/7976283/120075187-ee4d1580-c0a8-11eb-8131-8d7e5d267cfa.png">

**Comment by Lucas-C** [comment]
Thanks for the report @boghison!

Could you please provided your source code for this test?

**Comment by boghison** [comment]
@Lucas-C I got it from the `write_html` [documentation](https://pyfpdf.github.io/fpdf2/reference/write_html.html). I also tried it with the example [here](https://pyfpdf.github.io/fpdf2/HTML.html) by changing the first paragraph to `<p align="right"><b>Hello</b> world. <u>I am</u> <i>tired</i>.</p>`:
<img width="1205" alt="Screen Shot 2021-05-29 at 18 32 59" src="https://user-images.githubusercontent.com/7976283/120076005-4cc7c300-c0ac-11eb-8478-579f57311d9b.png">

PS Thank you for your work!

**Comment by boghison** [comment]
I think it’s because aligned paragraphs get written with `multi_cell`, so this might be related to  #108

**Comment by Lucas-C** [comment]
You're totally right, implementing #108 would help solving this!

I'll try to get back to this other issue in the next weeks.

**Comment by Lucas-C** [comment]
Quick update: now pending on https://github.com/PyFPDF/fpdf2/issues/171

**Comment by Lucas-C** [comment]
Quick status update: solving this would require rendering the whole `<p>` block with `FPDF.multi_cell()`.
But how to combine that with parsing of HTML tags like `<b>` or `<u>` inside the paragraph?
A solution could be to convert those to Markdown markers, but that's not an elegant solution...

https://github.com/PyFPDF/fpdf2/issues/91 is also closely related

**Comment by gmischler** [comment]
I've just checked in #897, which should solve this problem.
