### ISSUE TITLE
Vertically align Text in a Cell or Multicell

### ISSUE THREAD

**Issue by johann-su** [py-pdf/fpdf2#210]
Is there an option to change the vertical alignment of text inside a multicell from center to top or bottom?

I am using them to create a table and it would be very helpful to have the ability to change the vertical alignment of the text inside the table rows.

<img width="577" alt="Bildschirmfoto 2021-08-25 um 20 33 55" src="https://user-images.githubusercontent.com/48410810/130846187-d441237f-f8a5-418e-80de-c96077963d1b.png">

**Comment by Lucas-C** [comment]
Thanks for your explanation. I think I understand precisely the feature you want and why.
I agree that an option to align the text to the top, bottom or center of the cell
would be great. Again, PRs are welcome to implement that!

**Comment by Lucas-C** [comment]
For reference, @RubendeBruin is working on an implementation that will solve this in https://github.com/PyFPDF/fpdf2/pull/797

Reviews & comments on this PR are welcome!

**Comment by RubendeBruin** [comment]
@johann-su 
Vertical alignment functionality has been merged into master and will be included in the next release.
