### ISSUE TITLE
Change default background to transparent in templates

### ISSUE THREAD

**Issue by gmischler** [py-pdf/fpdf2#249]
Currently most template elements have a solid background with a default color of white, with no way to turn that off. There's no technical necessity for that as far as I can see, it probably just wasn't considered in the original design.

I would like to make a slightly backwards incompatible modification, and change the default to transparent. In effect, when you leave the background field empty in a csv file, or leave it away/set it to None in dicts, cells will be created with `fill=False`, rects get a `style='D'` instead of `'FD'`, and so on. I don't think the barcode types currently even have a background.

Would this be an acceptable change of semantics?
I don't know if many people actually draw overlapping elements with templates, which is the only situation where it actually matters. And if you want eg. a rect to obstruct whatever is behind it, then it's probably good practise to give it an explicit background color anyway.

I like flexible tools, and this would make the templates yet a bit more flexible again...

**Comment by Lucas-C** [comment]
Good idea, I agree with this change!
Sound a better usage model, and not something we really want backward compatibility for.
Would you submit a PR @gmischler ?

**Comment by gmischler** [comment]
I'm on it, and maybe some more template improvements along the way...
