### ISSUE TITLE
Feature request: set padding in a table cell

### ISSUE THREAD

**Issue by Rahulscan** [py-pdf/fpdf2#791]
i want to set margins or add padding to a cell which is in a table 
can it be added individually to a cell ?

**Comment by Lucas-C** [comment]
Hi @Rahulscan!

Sadly no, `fpdf2` currently does not offer table cell padding...
This would be very handy though! It could be a nice feature to have.

I recently created a PR to introduce an optional gutter betwen table cells:
https://github.com/PyFPDF/fpdf2/pull/787

This is not released yet, but will be part of the next version of `fpdf2`.

**Comment by RubendeBruin** [comment]
I did run into this as well.
Associated issue (for me) is that the row-height is identical to the line-height for multi-line cells.

Think I can solve both issues in one go.

**Comment by RubendeBruin** [comment]
@Rahulscan , do you need padding to be definable per cell or can all cells have the same padding?

**Comment by Rahulscan** [comment]
@RubendeBruin yes, i want the padding definable per cell !!
it that can be done, It'll be wonderful !!

**Comment by RubendeBruin** [comment]
Cando!

```
def test_padding_per_cell(tmp_path):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Times", size=12)

    red = (255, 100, 100)
    black = (0, 0, 0)

    deathstyle = FontFace(color=black, fill_color=red)

    with pdf.table(line_height = pdf.font_size,padding=2) as table:
        for irow in range(5):
            row = table.row()
            for icol in range(5):
                datum = "Circus"

                if irow == 3 and icol %2 == 0:
                    row.cell("custom padding", style=deathstyle, padding = (2*icol,8,8,8))
                else:
                    row.cell(datum)
```

<img width="506" alt="image" src="https://github.com/PyFPDF/fpdf2/assets/34062862/994b832c-69aa-4597-b491-17b2e9dde638">

**Comment by RubendeBruin** [comment]
@Rahulscan , can you check to pull request and see if it suits your needs?

**Comment by Rahulscan** [comment]
@RubendeBruin I went through ur request and as per my understanding i can specify the top, bottom, left, right individually if i want to do. I think it will do. Thanks for your help !!
