### ISSUE TITLE
Possible to create a new release?

### ISSUE THREAD

**Issue by arryon** [py-pdf/fpdf2#856]
Hi! This might be an impertinent question, and do let me know if there's some sort of release schedule, but I was wondering if it's possible to create a new release for fpdf2. The last one is from April 28, and there have been some bug fixes in the meantime that I'm interested in using.

Have a great day!

**Comment by Lucas-C** [comment]
Hi @arryon!

Your question is totally legitimate, you were right to ask 😊

I was hoping to merge some of the currently open PR before performing a new release,
especially #797, #820 & #851 that would provide useful fixups or new features.

Anyway, I'll peform a new release by the end of the month.

**Comment by arryon** [comment]
Hi, that makes perfect sense. Thanks for you reply, and looking forward to the release in any case 🤞

**Comment by RubendeBruin** [comment]
Yes, I'm back so will continue on #797

**Comment by Lucas-C** [comment]
Given that neither #797, #820 or #851 has been merged yet,
I'm goind to wait for a few more days before publishing a new release.

**Comment by Lucas-C** [comment]
Now that #820 & #872 have been merged, I plan to perform a release on Friday

**Comment by Lucas-C** [comment]
A new release has been published! https://github.com/py-pdf/fpdf2/releases/tag/2.7.5
