### ISSUE TITLE
New feature: Handle bidirectional text

### ISSUE THREAD

**Issue by andersonhc** [py-pdf/fpdf2#882]
Since text shaping was implemented, fpdf2 can correctly render text in left to right (LTR) or right to left (RTL) direction.
However, if the text provided has both RTL and LTR on the same string, fpdf2 is not applying the bidirectional rules to render the text, as pointed on #549
The problem happens because Harfbuzz will shape the text in one direction only.
If we apply the BIDI algorithm to the input string and break the direction changes into different fragments it should solve this issue as they will be rendered separately.

References:
https://www.w3.org/International/articles/inline-bidi-markup/uba-basics
https://en.wikipedia.org/wiki/Bidirectional_text

Implementations of the BIDI algorithm:
https://github.com/fribidi/fribidi
https://github.com/MeirKriheli/python-bidi

**Comment by mihir1739** [comment]
Can I work on this if possible please assign this to me.

**Comment by gmischler** [comment]
Welcome to fpdf2, @mihir1739 !

> Can I work on this if possible please assign this to me.

This issue is currently being worked on in #972.
Maybe you can find another interesting issue?

**Comment by andersonhc** [comment]
@marcstober
I am closing this issue as #1096 is now merged and released on 2.7.8
Can you please take a look and do some tests with bidirectional text?

**Comment by marcstober** [comment]
@andersonhc it's working! Thank you for your long-standing help with this issue.

Would it be useful for me to add my test file somewhere (an updated version of what I'd posted in #549)?

I noticed that selecting the text in a BIDI, RTL paragraph in Acrobat is a bit funny with my test file, and more generally, I'm not sure how fpdf2 knows whether a paragraph is a LTR or RTL paragraph (something I often switch manually in word processing apps). But this might be something I just need to read up the docs or something, and I can always file a new issue for any edge case. Overall I'm happy to see this working and now can go back to some side projects I set aside back when I ran into this over a year ago!

**Comment by andersonhc** [comment]
> @andersonhc it's working! Thank you for your long-standing help with this issue.
> 
> Would it be useful for me to add my test file somewhere (an updated version of what I'd posted in #549)?
> 
> I noticed that selecting the text in a BIDI, RTL paragraph in Acrobat is a bit funny with my test file, and more generally, I'm not sure how fpdf2 knows whether a paragraph is a LTR or RTL paragraph (something I often switch manually in word processing apps). But this might be something I just need to read up the docs or something, and I can always file a new issue for any edge case. Overall I'm happy to see this working and now can go back to some side projects I set aside back when I ran into this over a year ago!

I just did a small PR adding the option to force paragraph direction. Here is the test file:
https://github.com/py-pdf/fpdf2/blob/master/test/text_shaping/bidi_paragraph_direction.pdf

Also updated the Text Shaping documentation.
