### ISSUE TITLE
Inconsistent vertical alignment for text in tables

### ISSUE THREAD

**Issue by RubendeBruin** [py-pdf/fpdf2#893]
For tables in which the row-height is governed by text, the text of other cells is aligned in the center:
(test_table_with_multiline_cells)

<img width="549" alt="image" src="https://github.com/py-pdf/fpdf2/assets/34062862/becd4ef2-2201-49d1-89ca-c3d9600582a3">

But if an image governs the height, then the text is aligned to the top:
(test_table_with_multiline_cells_and_images)

<img width="388" alt="image" src="https://github.com/py-pdf/fpdf2/assets/34062862/5d97c00e-2885-4cab-b32c-68c13b67aef2">

I think the alignment should be center instead:
<img width="374" alt="image" src="https://github.com/py-pdf/fpdf2/assets/34062862/2a742c2c-17cf-4400-8b7a-5136a65d1261">

This changed default behaviour is implemented in #797

**Comment by RubendeBruin** [comment]
please let me know if this is a desirable change in default behavior, if so then I will update the reference pdfs accordingly.

**Comment by Lucas-C** [comment]
> please let me know if this is a desirable change in default behavior, if so then I will update the reference pdfs accordingly.

Yes, I think that have a consistent behaviour would be nice!
Pick whichever default behaviour seems better to you.

Moreover, you PR will give users fine-grained control over text alignement in cells,
so they will be able to adjust it by themselves.

Please also include a mention of this change in the `Changed` section of the `CHANGELOG.md`

**Comment by blaketeres** [comment]
I am seeing inconsistent vertical alignment regardless with just text in other columns. I can provide an example if needed.

**Comment by RubendeBruin** [comment]
@blaketeres , vertical alignment option is included in #797 

If you can provide some examples then we can check if they are also inconsistent after #797 .

**Comment by blaketeres** [comment]
I see :) thanks. I'll follow there and only post back here if I'm still having issues afterwards

**Comment by RubendeBruin** [comment]
Solved in #797
