### ISSUE TITLE
Differences of PDF output for OTF files

### ISSUE THREAD

**Issue by gmischler** [py-pdf/fpdf2#899]
**Error details**
On my system, currently four tests fail, all font related:

    =========================== short test summary info ===========================
    FAILED test/encryption/test_encryption.py::test_encrypt_font - AssertionError
    FAILED test/fonts/test_add_font.py::test_add_font_otf - AssertionError
    FAILED test/fonts/test_charmap.py::test_charmap_first_999_chars[Quicksand-Regular.otf]
    FAILED test/fonts/test_font_fallback.py::test_fallback_font_with_overriden_get_fallback_font
    = 4 failed, 1152 passed, 1 skipped, 1 deselected, 2 xfailed, 6 warnings in 370.86s (0:06:10) =

The culprits appear to be the included OTF fonts. They show some visible differences in the binary data, and in three cases they are a few bits longer.
The font files on my system look identical to the ones in the repository (I replaced one with the original, just to be sure).

My current PR just passed all the tests (including the four affected ones) on github, and there's a job with a nearly identical configuration included.

It is possible that the OTF file processing in harfbuzz is somehow locale dependent? That's the only significant difference of my local system I'm currently aware of. Other than that, I'm at a loss about the reasons.

**Minimal code**

```python
pytest --assert=plain
```

**Environment**
Please provide the following information:
* **Operating System**: Windows 10 (German language)
* **Python version**: 3.10
* **`fpdf2` version used**: upstream/master HEAD
* **uharfbuzz version used**: most recent (for Windows) 0.37.2

**Comment by andersonhc** [comment]
We had a discussion about this issue a couple weeks ago, it's a change on how FontTools handle OTF fonts that was introduced on FontTools 4.40.0.
Your local copy of FontTools must be older than 4.40 that's why the tests are failing.
Can you try updating it to the latest version?

**Comment by andersonhc** [comment]
https://github.com/py-pdf/fpdf2/pull/863

**Comment by gmischler** [comment]
Oh my, I forgot that we're still using fonttools when text shaping isn't enabled! 🤡 

I also hadn't followed #863 very closely. And I thought I had very recently updated all my dependencies, but apparently that was only the testing dependencies...

Works now, thanks for the pointer!
