### ISSUE TITLE
Python3.10 Compatibility: missing _cffi_backend

### ISSUE THREAD

**Issue by baldum** [py-pdf/fpdf2#910]
I'm getting a 
> ModuleNotFoundError: No module named '_cffi_backend'

when attempting to import fpdf2, and research has lead me to believe that this could be a version compatibility issue. I'm running Python3.10. Here is my output for 

> python --version

Python 3.10.6

> pip --version

pip 23.2.1

> pip freeze

AllanTools==2019.9
attrs==23.1.0
cffi==1.15.1
cmsis-pack-manager==0.5.2
contourpy==1.1.0
crcmod==1.7
cryptography==41.0.3
cycler==0.11.0
DateTime==4.7
defusedxml==0.7.1
exceptiongroup==1.1.3
fonttools==4.42.1
fpdf2 @ git+https://github.com/PyFPDF/fpdf2.git@b74a5906e4f114557ae26316ab5298c51ad6e858
grpcio==1.57.0
h5py==3.9.0
iniconfig==2.0.0
kiwisolver==1.4.5
libusb-package==1.0.26.2
MarkupSafe==2.1.2
matplotlib==3.6.1
numpy==1.23.1
packaging==23.1
pandas==2.1.0
Pillow==10.0.0
pluggy==1.3.0
protobuf==3.12.4
pycparser==2.21
pycryptodome==3.18.0
pyparsing==3.1.1
pytest==7.2.0
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0
ruamel.yaml.clib==0.2.7
scipy==1.11.2
six==1.16.0
tomli==2.0.1
tzdata==2023.3
zope.interface==6.0

Any help is appreciated

**Comment by gmischler** [comment]
fpdf2 does not use cffi, but I think the cryptography module does.
Can you import cryptography or just cffi by itself without an error?
In any case, this is most likely an issue with your cffi installation which you'll need to sort out.

**Comment by baldum** [comment]
> fpdf2 does not use cffi, but I think the cryptography module does. Can you import cryptography or just cffi by itself without an error? In any case, this is most likely an issue with your cffi installation which you'll need to sort out.

I can import both. The thing is that this conflict only comes up when replacing fpdf with fpdf2. Everything runs fine with fpdf installed, but if I uninstall and then install fpdf2, I cannot `import fpdf` anymore

**Comment by Lucas-C** [comment]
Hi @baldum 🙂

Unless you have more information to provide regarding this issue, I will probably end up closing it.

Regards
