### ISSUE TITLE
Multi-cell hyperlink with Markdown followed by \n

### ISSUE THREAD

**Issue by mariostg** [py-pdf/fpdf2#916]
Regarding this example : https://py-pdf.github.io/fpdf2/Links.html#hyperlink-with-fpdfmulti_cell

If I use a \n after **website** like so:

```python
from fpdf import FPDF

pdf = FPDF()
pdf.set_font("helvetica", size=24)
pdf.add_page()
pdf.multi_cell(
    pdf.epw,
    txt="**Website:**\n[fpdf2](https://py-pdf.github.io/fpdf2/) __Go visit it!__",
    markdown=True,
)
pdf.output("hyperlink.pdf")
```

txt is rendered as expected, but the following does not work as expected;  the link is not rendered and the new line neither.  See \n just after the link

```python
from fpdf import FPDF

pdf = FPDF()
pdf.set_font("helvetica", size=24)
pdf.add_page()
pdf.multi_cell(
    pdf.epw,
    txt="**Website:** [fpdf2](https://py-pdf.github.io/fpdf2/)\n__Go visit it!__",
    markdown=True,
)
pdf.output("hyperlink.pdf")
```

**Environment**
Mac OSX
Python version: 3.11.1
fpdf2 2.7.5

**Comment by Lucas-C** [comment]
Thank you @mariostg for reporting this bug!

I opened #917 to fix it

**Comment by Lucas-C** [comment]
It's fixed, but not released yet.

You can test it by installing `fpdf2` from git, this way:

    pip install git+https://github.com/py-pdf/fpdf2.git@master

Also, as a workaround in the meantime, you can simply insert a space before the `\n` character
