### ISSUE TITLE
pdf.set_display_mode(zoom=...) not working

### ISSUE THREAD

**Issue by macdeport** [py-pdf/fpdf2#926]
I discovered fpdf2 and tried it out. Thanks for this interesting library.

Describe the bug

**Error details**
I couldn't make 

  `pdf.set_display_mode(zoom=25)`

works to produce a PDF that opens at a scale of 25%...

**Minimal code**
Please include some minimal Python code reproducing your issue:
```python
from fpdf import FPDF
pdf = FPDF()
pdf.add_page()
pdf.set_display_mode(zoom=50)
pdf.output('test_zoom.pdf')
```
If you don't know how to build a minimal reproducible example, please check this tutorial: https://stackoverflow.com/help/minimal-reproducible-example

**Environment**
Please provide the following information:
* **Operating System**:  Mac OSX
* **Python version**: Python 3.9.18
* **`fpdf2` version used**: 2.7.5

**Proposed fix**
If I'm not mistaken...

In output.py > _finalize_catalog() after :
```python
 # zoom_mode is a number, not one of the allowed strings:
 zoom_config = ["/XYZ", "null", "null", str(fpdf.zoom_mode / 100)]
```
add :
```python
    zoom_config = [
        pdf_ref(first_page_obj.id),
        *zoom_config]
```

**Comment by andersonhc** [comment]
Thank you @macdeport for reporting this bug.

I was able to reproduce it and your proposed fix seems to solve the problem. Do you want to submit a PR fixing the bug?

We have documented our [development guidelines](https://py-pdf.github.io/fpdf2/Development.html) if you want to take a look.

**Comment by Lucas-C** [comment]
Thank you for reporting this @macdeport

We already have some unit tests regarding the `zoom`:
https://github.com/py-pdf/fpdf2/blob/master/test/metadata/test_display_mode.py
But it seems that we did not test setting a numeric value.

An extra test could be added regarding this case.
If you do not wish to submit a PR, one of the current maintainers can do it,
but we often like to ask `fpdf2` users if they want to use this opportunity to contribute to the project 🙂

**Comment by macdeport** [comment]
I would have been happy to contribute more, and it could have been instructive for me, but I'm too busy at the moment... thank you for what you do and for your offer.

**Comment by andersonhc** [comment]
> @Lucas-C @andersonhc I would have been happy to contribute more, and it could have been instructive for me, but I'm too busy at the moment... thank you for what you do and for your offer.

No worries. I just opened a PR to fix the bug and added an automated test on this feature to reduce the chances of it breaking again in the future.

Thanks again for taking the time to create the minimal code and investigate the fix.
