### ISSUE TITLE
set_fill_color fills the table column and html table

### ISSUE THREAD

**Issue by erdikilic** [py-pdf/fpdf2#932]
When I write `pdf.set_fill_color(*color)` for different task before the table, It fills columns with that color instead of the color given in the `pdf.table(**params)` with `params = { "cell_fill_color": (247, 248, 253), "cell_fill_mode":"COLUMNS", }`

**Example Code**
```python
from fpdf import FPDF
from fpdf.fonts import FontFace

pdf = FPDF()
pdf.add_page()

pdf.set_fill_color((126, 217, 87))
pdf.rect(x=10, y=15, w=185, h=8, style="F", round_corners=("TOP_RIGHT", "BOTTOM_RIGHT", "BOTTOM_LEFT", "TOP_LEFT"), corner_radius=8*2.5)

params = {
    "text_align": ("LEFT", "CENTER", "CENTER", "CENTER", "LEFT"),
    "width": 185,
    "col_widths": (50, 20, 20, 20, 75),
    "line_height":9,
    "cell_fill_color": (247, 248, 253),
    "cell_fill_mode":"COLUMNS",
    "borders_layout":"HORIZONTAL_LINES",
    "headings_style": FontFace(emphasis="B", color=(64,64,64), fill_color=(255,255,255), size_pt=12),
    }

summary_text = (
    ("A", "B", "C", "D", "E"),
    ("F", "", "", "", ""),
    ("G", "", "", "", ""), )

pdf.set_font(family="Times", style="B", size=12)
pdf.set_xy(15, 35)
with pdf.table(**params) as table:
    for data_row in summary_text:
        row = table.row()
        for data_cell in data_row:
            row.cell(data_cell)

pdf.output("output.pdf")
```

**Environment**
* **Operating System**: Ubuntu 22.04
* **Python version**: 3.11.4`
* **`fpdf2` version used**: 2.7.5

[output.pdf](https://github.com/py-pdf/fpdf2/files/12735309/output.pdf)
[output_expected.pdf](https://github.com/py-pdf/fpdf2/files/12735310/output_expected.pdf)

**Comment by Lucas-C** [comment]
Hi @erdikilic

I'll get a look at this and get back to you tomorrow 🙂

**Comment by Lucas-C** [comment]
I was able to reproduce the problem and opened #934 to fix this.

However there are still a couple of things to figure out / clarify, that is how should `fpdf2` combine:
* `FPDF.fill_color`
* `cell_fill_color` / `cell_fill_mode` provided to `FPDF.table()`
* `.fill_color` of `headings_style` provided to `FPDF.table()`

**Comment by erdikilic** [comment]
Thanks for the help. I'm looking forward to updates.
