### ISSUE TITLE
ln() does nothing at the beginning of a new file

### ISSUE THREAD

**Issue by gmischler** [py-pdf/fpdf2#937]
**Error details**
`ln()` moves `self.y` either by its "h" argument or by `self._lasth`.
At the beginning of a file, _lasth is 0, so 

**Minimal code**
```python
from fpdf import FPDF
pdf = FPDF()
print(pdf.y)
pdf.ln()
print(pdf.y)
```

Expected result:
```
10
14.23333
```
Actual result:
```
10
10
```

Since we have a default font size of 12 points, I would expect self.y to get moved by that much in this situation.
I tried to fix that in #897, but then noticed that quite a few of our tests start with an ineffective ln() (usually within a loop where it later does have an effect). I didn't want to change all those otherwise unrelated tests (under shapes), so I'm bringing it up here.

The fix would be to simply use `self.font_size` if the other two values (the parameter "h" or `self._lasth`) are None and 0.

**Comment by Lucas-C** [comment]
> The fix would be to simply use `self.font_size` if the other two values (the parameter "h" or `self._lasth`) are None and 0.

I agree that this should be fixed.

However wouldn't it be better to simply initialize `self._lasth` to `self.font_size`?

**Comment by gmischler** [comment]
> However wouldn't it be better to simply initialize `self._lasth` to `self.font_size`?

```python
pdf = FPDF()
pdf.set_font("helvetica", size=36)
pdf.ln()
```

By how much would `pdf.y` move down in that case?
I think we really need to use the current value of `pdf.font_size`.

**Comment by Lucas-C** [comment]
> I think we really need to use the current value of `pdf.font_size`.

Alright!

And let's use your sample in a unit test 🙂
