### ISSUE TITLE
Support tables with multiple header rows

### ISSUE THREAD

**Issue by SandraFer** [py-pdf/fpdf2#938]
**Please explain your intent**
The `Table` class supports defining the first row as header. However, this is limited to only the first row. For an automatic report we generate at work it would be lovely to be able to define the top two rows as headers. I played around with the code and it seems fairly straightforward to extent this to an arbitrary number of header rows.

**Describe the solution you'd like**
Currently, the `first_row_as_headings` argument is used to set the first row to header or standard row. I propose to add a new argument to the table class to define a number of header rows (e.g. `number_of_header_rows`). The default value should be `1` to align with the default `first_row_as_headings=True`.

In the long run, this new argument could make `first_row_as_headings` obsolete. For backwards compatibility, both arguments should be supported for now. There needs to be a decision of how to handle conflicting arguments (e.g. `first_row_as_headings=False` and `number_of_header_rows=1`). 

I am sure there are other things to be considered which I am not aware of atm 😄 .

**Additional context**
I actually played around an a local branch and have some first working version. With this snippet:
```python
from fpdf import FPDF
from fpdf.fonts import FontFace

pdf = FPDF()
pdf.set_font('Times', size=12)
pdf.add_page()
pdf.multi_cell(w=0, txt='Feature request: support tables with multiple header rows, like the following example.')
pdf.ln()
heading_style = FontFace(emphasis="Bold", fill_color=(100, 100, 200))

table_data = [[['Fruits', 3], ['Dairy', 3]],
              ['Apple', 'Banana', 'Cherry', 'Cheese', 'Milk', 'Yogurt'],
              [1,2,3,4,5,6],
              [1,2,3,4,5,6],
              [2,3,4,5,6,7],
              [2,3,4,5,6,7],
              [3,4,5,6,7,8],
              [3,4,5,6,7,8],
              ]

for i in range(2):
    with pdf.table(number_of_headers=2, headings_style=heading_style) as tab:
        for data in table_data:
            row = tab.row()
            for cell in data:
                if isinstance(cell, list):
                    row.cell(text=cell[0], colspan=cell[1])
                elif isinstance(cell, int):
                    row.cell(text=str(cell))
                else:
                    row.cell(text=cell)
    if i == 0:
        pdf.set_y(220)
        pdf.multi_cell(w=0, txt='Page breaks should be handled as follows:')
        pdf.ln()

pdf.output('test.pdf')
```

I get [test.pdf](https://github.com/py-pdf/fpdf2/files/12783046/test.pdf).

If the maintainers agree that this feature is useful I am happy to finish implementation and open a PR.

**Comment by Lucas-C** [comment]
Hi @SandraFer and welcome 🙂

Thank you for this feature suggestion!

It would be a very welcome addition to `fpdf2`.
You can submit a PR and I'll review it.

Some thoughts:
* maybe `headings_rows_count` would be shorter than `number_of_header_rows`. Also, _headings_ and _headers_ are different things in `fpdf2`, so I'd prefer to stick with _headings_ regarding tables top rows.
* I agree that `headings_rows_count=0` could replace `first_row_as_headings=False`. We will handle this deprecation later on, after your PR is merged. For now, if `first_row_as_headings=False` and `number_of_header_rows` is set to a non-zero value, a `ValueError` should be raised by the `Table` constructor

**Comment by Lucas-C** [comment]
@allcontributors please add @SandraFer for ideas

**Comment by gmischler** [comment]
Indeed, that's a very good idea! Being able to group headings and subheadings is very helpful to format non-trivial tables.

For a moment I was considering whether we should actually allow arbitrary rows to become headers, like HTML does (often used for repeating the headers after a certain number of data rows). But then, HTML doesn't have page breaks, which we do. Page breaks offer a natural opportunity to repeat the original headers, which we also do. So I guess we're fine with a slightly more rigid approach to simplify things.

Apparently @Lucas-C likes the word "count"... :wink: (we had a similar conversation elsewhere.)
 I don't think it is the right word here either though. We're not counting the headers, we're specifying their number.
But I agree that the specified number should override the boolean option, maybe except when it is the default of 1 (for backwards compatibility).

**Comment by Lucas-C** [comment]
> Apparently @Lucas-C likes the word "count"... 😉 (we had a similar conversation elsewhere.)
> I don't think it is the right word here either though. We're not counting the headers, we're specifying their number.
> But I agree that the specified number should override the boolean option, maybe except when it is the default of 1 (for backwards compatibility).

Alright, let's go for `number` instead of `count` 😄

And regarding page breaks, it would be nice to have a unit test with two heading rows and a page break.

**Comment by gmischler** [comment]
Whenever `headings_rows_number` (maybe `num_heading_rows`?) is anything other than 1 (the default), I would probably just ignore `first_row_as_headings`. You could even make it an error to set `first_row_as_headings` to False in that case.
This changes nothing for existing users who are already using `first_row_as_headings`, but encourages new users to prefer the more flexible new parameter.

It's easiest to add new tests to the existing file. but if you prefer to eg. move all the tests dealing with headings to a seperate file, then that's up to you. Testing the repetigion of multiple heading lines on the next page is obvious, but if you can think of any other weird combinations of input that a user might try (especially those with non-obvious effects), just add test for those as well.

**Comment by Lucas-C** [comment]
> Whenever `headings_rows_number` (maybe `num_heading_rows`?) is anything other than 1 (the default), I would probably just ignore `first_row_as_headings`. You could even make it an error to set `first_row_as_headings` to False in that case.
> This changes nothing for existing users who are already using `first_row_as_headings`, but encourages new users to prefer the more flexible new parameter.

I agree.
I'll just add that raising an error is better that silently ignoring `first_row_as_headings`, which could cause some misunderstanding to our users.
