### ISSUE TITLE
.html file intead an string with the code

### ISSUE THREAD

**Issue by pedrogiroldo** [py-pdf/fpdf2#942]
Hi! I need to know if fpdf2 has some way to create a pdf using an .html file instead an string with the html

**Comment by gmischler** [comment]
Hi @pedrogiroldo,

You have the power of Python at your fingertips. What keeps you from just reading the file into a string yourself?
Btw.: None of the other text rendering methods of fpdf2 accept a file in place of a string, why should `write_html()` be different about that?

**Comment by Lucas-C** [comment]
To expand on @gmischler answer, there is a starting point for you:
```python
from fpdf import FPDF

pdf = FPDF()
pdf.set_font("Helvetica", size=16)  # You could also use a unicode fonts that support more characters
pdf.add_page()
with open("index.html") as html_file:
    pdf.write_html(html_file.read())
pdf.output("repro.pdf")
```

**Comment by pedrogiroldo** [comment]
Thanks for that! You can close👍👍
