### ISSUE TITLE
add_font is not adding Arial font or set_font is not finding it?

### ISSUE THREAD

**Issue by abubelinha** [py-pdf/fpdf2#955]
I just want to use the Arial font, 
[EDIT: my first try was just to "set" it, but didn't work (see code in [comments below](https://github.com/py-pdf/fpdf2/issues/955#issuecomment-1760214676)). 
So I thought I needed to "add" one of the TTF fonts installed on my system, and then "set" it.]
  
Looked into several places before:
https://pyfpdf.readthedocs.io/en/latest/reference/add_font/index.html
https://github.com/py-pdf/fpdf2/discussions/233#discussioncomment-4791279
https://www.youtube.com/watch?v=o7vixt2mVdo
https://py-pdf.github.io/fpdf2/Unicode.html

I am not getting an error in `add_font` line, so I guess it worked, and font should be available to FPDF.
But then `set_font` throws a "font substitution warning", but I don't know why:

**Error details**
```
mytest.py:64: UserWarning: Substituting font arial by core font helvetica
  pdf.set_font("Arial", "B", 16)
```

**Minimal code**
Please include some minimal Python code reproducing your issue:
```python
from fpdf import FPDF
pdf = FPDF()
pdf.add_page()
pdf.add_font("Arial", "", r"C:\Windows\Fonts\Arial.ttf")
pdf.set_font("Arial", "B", 16)
pdf.cell(40, 10, "Hello Arial!")
pdf.output("fpdf-test.pdf")
```
I can't figure out what is wrong

**Environment**
Please provide the following information:
* **Operating System**: Windows 7 64bit
* **Python version**: 3.8.7
* **`fpdf2` version used**: 2.7.6

**Comment by andersonhc** [comment]
The problem is "Arial" is a reserved name for a core font.
If you use another name it will be OK.

try:

pdf.add_font("Arial_TTF", "", r"C:\Windows\Fonts\Arial.ttf")
pdf.set_font("Arial_TTF", "B", 16)

**Comment by abubelinha** [comment]
Thanks @andersonhc but that's not working either.
Actually, I recall I made this `add_font` test because I was not being able to use the "Arial" font by simply calling `set_font`.
Look at this:

```Python
def fpdf_font_test():
  from fpdf import FPDF
  pdf = FPDF()
  pdf.add_page()
  pdf.set_font("Arial", "B", 16)   # WARNING: 
  # the above "reserved name for a core font" is not working: it gets substituted
  pdf.cell(40, 10, "Hello Arial!")
  pdf.add_font("Arial_TTF", "", r"C:\Windows\Fonts\Arial.ttf")
  pdf.set_font("Arial_TTF", "B", 16)  # NOW THIS RAISES AN ERROR
  pdf.cell(40, 20, "Hello Arial_TTF!")
  pdf.output("fpdf-test.pdf")
```
OUTPUT:
```
mytest.py:63: UserWarning: Substituting font arial by core font helvetica
  pdf.set_font("Arial", "B", 16)
Traceback (most recent call last):
  File "mytest.py", line 103, in <module>
    fpdf_font_test(); sys.exit()
  File "mytest.py", line 66, in fpdf_font_test
    pdf.set_font("Arial_TTF", "B", 16)
  File "C:\Python38\lib\site-packages\fpdf\fpdf.py", line 1922, in set_font
    raise FPDFException(
fpdf.errors.FPDFException: Undefined font: arial_ttfB - Use built-in fonts or FPDF.add_font() beforehand
```

**Comment by andersonhc** [comment]
On your example:

1) mytest.py:63: UserWarning: Substituting font arial by core font helvetica

This is not an error, it's just a warning that fpdf is replacing arial
by helvetica. Arial is an "alias" for helvetica - this comes from the
original PHP fpdf.

2)  fpdf.errors.FPDFException: Undefined font: arial_ttfB - Use
built-in fonts or FPDF.add_font() beforehand

This is an error because you are using bold "arial_ttf" and you didn't
define a bold version for this font.

To correct you could change your script like this:

```python

def fpdf_font_test():
  from fpdf import FPDF
  pdf = FPDF()
  pdf.add_page()
  pdf.set_font("Arial", "B", 16)   # WARNING:
  # the above "reserved name for a core font" is not working: it gets
substituted
  pdf.cell(40, 10, "Hello Arial!")
  pdf.add_font("Arial_TTF", "", r"C:\Windows\Fonts\Arial.ttf")

  pdf.add_font("Arial_TTF", "B", r"C:\Windows\Fonts\arialbd.ttf")
  pdf.set_font("Arial_TTF", "B", 16)  # NOW THIS RAISES AN ERROR
  pdf.cell(40, 20, "Hello Arial_TTF!")
  pdf.output("fpdf-test.pdf")

```

**Comment by abubelinha** [comment]
> it's just a warning that fpdf is replacing arial by helvetica. Arial is an "alias" for helvetica

OMG!!  Thanks a lot for clarifying (also for explaining the 2nd bold error). 
So _arial_ and _helvetica_ are just synonymous words for the same font?
I don't understand the reason for a warning, but I would express it differently (i.e. "_arial font is called helvetica in FPDF context_")

Instead of "_substituting font arial by core font helvetica_", which is a bit confusing message:  
It gives the impression that the requested arial font is not installed, so FPDF is going to use another font instead.

**Comment by gmischler** [comment]
Maybe it is time to finally get rid of those aliases?

Two reasons:

* **They are not documented anywhere.**
* For the original PHP FPDF with the goal of "shove stuff into a PDF file somehow", that "feature" may have made at least some sense. But the development push for fpdf2 has increasingly been (during the time I've been involved) to produce output that is as typographically correct as possible. Replacing "similar" fonts automatically (with a warning that hardly anyone sees) really doesn't make sense anymore in that context.

**Comment by Lucas-C** [comment]
I agree, removing those aliases also seem a good idea to me.
They are more confusing than helpful
