### ISSUE TITLE
Update Deprecated Parameter Name in README.md

### ISSUE THREAD

**Issue by rakesh-nj** [py-pdf/fpdf2#959]
Describe the bug

**Update Deprecated Parameter Name**
I encountered a DeprecationWarning while using the 'fpdf' library, indicating that the parameter 'txt' has been renamed to 'text' in version 2.7.6.

**Minimal code**
Please include some minimal Python code reproducing your issue:
```python
from fpdf import FPDF

pdf = FPDF()
pdf.add_page()
pdf.set_font('helvetica', size=12)
pdf.cell(txt="hello world")
# DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6

...
```

**Environment**
Please provide the following information:
* **Operating System**:  Linux (Ubuntu 22.04.2)
* **Python version**: 3.10.12
* **`fpdf2` version used**: 2.7.6

I would like to contribute to the project by submitting a pull request to update the README.md file and reflect the parameter name change from 'txt' to 'text.' Please let me know if this is an acceptable change, and I'm happy to work on the pull request.

**Comment by andersonhc** [comment]
Hi Rakesh,
Of course it an acceptable change, we'll be glad to receive and review your PR.
If you go on the github search bar and search for "txt=" you will find some tutorial and test files that weren't updated either - can you add them on your PR too?

**Comment by rakesh-nj** [comment]
Definitely . Could you please assign this issue to me?

**Comment by Lucas-C** [comment]
@allcontributors please add @rakesh-nj for documentation
