### ISSUE TITLE
Wrong link for DejaVu fonts in docs

### ISSUE THREAD

**Issue by StianTorjussen** [py-pdf/fpdf2#966]
https://github.com/py-pdf/fpdf2/blob/a4d05f5f5cdfd6451441f9465e1ae65d438836f8/docs/Unicode.md?plain=1#L15

I believe the correct link should be: `https://dejavu-fonts.github.io/`

The current link goes to a french blog. Kinda looks like someone hijacked the domain, but I dunno.

**Comment by andersonhc** [comment]
Hi @StianTorjussen ,
Thanks for reporting this.
Do you want to start a PR correcting the link?
