### ISSUE TITLE
Using font emphasis 'B' in table headings require the corresponding font style to be added using add_font()

### ISSUE THREAD

**Issue by Kh4Rj0** [py-pdf/fpdf2#976]
Hello.

**Error details**
I always get 

```
Traceback (most recent call last):
  File "/home/user/bin/table-to-pdf.py", line 43, in <module>
    create_pdf(data)
  File "/home/user/bin/table-to-pdf.py", line 32, in create_pdf
    with pdf.table() as table:
  File "/usr/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/home/user/.venv/fpdf/lib/python3.11/site-packages/fpdf/fpdf.py", line 4883, in table
    table.render()
  File "/home/user/.venv/fpdf/lib/python3.11/site-packages/fpdf/table.py", line 218, in render
    raise FPDFException(
fpdf.errors.FPDFException: Using font emphasis 'B' in table headings require the corresponding font style to be added using add_font()
```
when try to create pdf with the following code

**Minimal code**

```python
from fpdf import FPDF

...

def create_pdf(table_data):
    pdf = FPDF()
    pdf.add_page(orientation='landscape', format='A4')
    pdf.add_font('LiberationSans-Regular', '', 'LiberationSans-Regular.ttf')
    pdf.add_font('LiberationSans-Bold', 'B', 'LiberationSans-Bold.ttf')
    pdf.set_font('LiberationSans-Regular', '', 14)
    # pdf.set_font('LiberationSans-Bold', 'B', 14)
    with pdf.table() as table:
        for data_row in table_data:
            row = table.row()
            for datum in data_row:
                row.cell(datum)
    pdf.output('/home/user/test.pdf')

...
create_pdf(data)
```
However if I uncomment `pdf.set_font('LiberationSans-Bold', 'B', 14)` everything works fine except all text in pdf is bold. I don't need that.

**Environment**
Debian 12.1
Python 3.11.2
fpdf2 2.7.6

**Comment by gmischler** [comment]
Welcome to fpdf2, @Kh4Rj0 !

> ```python
>     pdf.add_font('LiberationSans-Regular', '', 'LiberationSans-Regular.ttf')
>     pdf.add_font('LiberationSans-Bold', 'B', 'LiberationSans-Bold.ttf')
>     pdf.set_font('LiberationSans-Regular', '', 14)
> ```

In calls to `add_font()` and `set_font()`, the family name argument must not include the style, or fpdf2 won't know that they belong together. Using the same name is what makes them a family after all, and the style is already supplied by its own argument:

```python
pdf.add_font('LiberationSans', '', 'LiberationSans-Regular.ttf')
pdf.add_font('LiberationSans', 'B', 'LiberationSans-Bold.ttf')
pdf.set_font('LiberationSans', '', 14)
```

I guess the documentation could be a bit more explicit about that...

**Comment by gmischler** [comment]
I already had PR #975 open to update the documentation on Unicode fonts, so I just added a section explaining how to load and set fonts, which should make things sufficiently clear.

**Comment by Kh4Rj0** [comment]
Thank you, @gmischler
