### ISSUE TITLE
Improve Error Handling in scripts/install-verapdf.sh

### ISSUE THREAD

**Issue by rakesh-nj** [py-pdf/fpdf2#983]
**Enhance error handling capabilites**
Make the install-verapdf.sh script more robust, user-friendly, and reliable by enhancing its error handling mechanisms. This should lead to a better user experience and easier maintenance of the script.

**Describe the solution you'd like**
The desired solution is to enhance error handling in the script by providing clear and informative error messages, enabling graceful error exits with meaningful exit codes, and ensuring consistent error handling throughout. This will improve user understanding, facilitate easier troubleshooting, and prevent silent failures.

**Additional context**
```bash
#!/bin/bash

# Improved veraPDF installation script for Linux

# Define variables
verapdf_download_url="https://software.verapdf.org/rel/1.22/verapdf-greenfield-1.22.3-installer.zip"
installation_path="$PWD/verapdf"

# Function to check if a command is available
command_exists() {
  command -v "$1" > /dev/null 2>&1
}

# Check for dependencies
if ! command_exists wget || ! command_exists unzip; then
  echo "Error: Please install 'wget' and 'unzip' before running this script."
  exit 1
fi

# Cleanup previous installations
rm -rf verapdf-*
rm -rf "$installation_path"

# Download veraPDF installer
wget --quiet "$verapdf_download_url"

# Check for download errors
if [ $? -ne 0 ]; then
  echo "Error: Download failed. Please check your internet connection and try again."
  exit 1
fi

# Extract the installer
unzip verapdf*installer.zip

# Check for extraction errors
if [ $? -ne 0 ]; then
  echo "Error: Extraction failed. Please check the downloaded file and try again."
  exit 1
fi

# Install veraPDF
(
  # Press 1 to continue, 2 to quit, 3 to redisplay:
  echo 1
  # Select the installation path:
  echo "$installation_path"
  # Enter O for OK, C to Cancel:
  echo O
  # Press 1 to continue, 2 to quit, 3 to redisplay:
  echo 1
  # Include optional pack 'veraPDF Corpus and Validation model' - Enter Y for Yes, N for No:
  echo N
  # Include optional pack 'veraPDF Documentation' - Enter Y for Yes, N for No:
  echo N
  # Include optional pack 'veraPDF Sample Plugins' - Enter Y for Yes, N for No:
  echo N
  # Press 1 to continue, 2 to quit, 3 to redisplay:
  echo 1
) | verapdf-*/verapdf-install

# Check for installation errors
if [ $? -ne 0 ]; then
  echo "Error: Installation failed. Please check the installation settings and try again."
  exit 1
fi

# Clean up downloaded files
rm -rf verapdf-*

# Successful installation message
echo "veraPDF has been successfully installed at: $installation_path"

```
if it is an acceptable change , could you please assign it to me ?
Thank you🙂

**Comment by Lucas-C** [comment]
Hi @rakesh-nj

Thank for your interest in `fpdf2`, and for suggesting an improvment!

`scripts/install-verapdf.sh` is a very minor script in this project.
It's usually only used in the GitHub Actions pipeline, and I am probably the only perso who ever used it onmy computer 😅

How did you get to look at this script exactly? Why did you have to install VeraPDF this way?

The changes you suggested are relatively minor and I'm not sure that they are really needed.

More annoying, you got rid og the `set -o pipefail -o errexit -o nounset -o xtrace` line in your script,
but that is a very import failsafe!

I encourage you to read those articles on this subject:
* http://redsymbol.net/articles/unofficial-bash-strict-mode/
* https://kvz.io/blog/bash-best-practices.html
* `set -eo pipefail` is also mentioned in https://gist.github.com/outro56/4a2403ae8fefdeb832a5

**Comment by Lucas-C** [comment]
Closing this issue for now
